### ISSUE TITLE
'Cannot read property 'forEach' of undefined' when using richTextResolver

### ISSUE THREAD

**Issue by nelsynelz** [storyblok/storyblok-nuxt#11]
Hey All, I'm running into an issue when using the richTextResolver from the storyapi. I followed the nuxt example [here](https://www.storyblok.com/docs/richtext-field) exactly.

Here is the error: 

```
TypeError
Cannot read property 'forEach' of undefined
```

Here is where the error is occuring: 
node_modules/core-js-pure/stable/instance/for-each.js

It's on Line 12 of the above file. 

```
module.exports = function (it) {
  var own = it.forEach;
  return it === ArrayPrototype || (it instanceof Array && own === ArrayPrototype.forEach)
    // eslint-disable-next-line no-prototype-builtins
    || DOMIterables.hasOwnProperty(classof(it)) ? forEach : own;
};
```

**Comment by P4sca1** [comment]
Same issue here. Also using nuxt.js.
`node_modules/storyblok-js-client/dist/richTextResolver.js` line `60`.
Trying to render my content like so:
`{{ $storyapi.richTextResolver.render(entry.body) }}`

**Comment by P4sca1** [comment]
@nelsynelz For me the issue was that I switched from markdown to rich text and Storyblok API still returned markdown. I needed to save the content one time manually so that the changes get applied.

**Comment by nelsynelz** [comment]
Appreciate the heads up! However I'm not even directly integrating yet via the web API, I manually took the "published JSON" via copy/paste. Here is my code...

```
<template>
    <div>
        <div v-html="richtext"></div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            text: {"story":{"name":"First Blog Post","created_at":"2020-01-02T20:52:29.559Z","published_at":"2020-01-27T15:11:55.721Z","alternates":[],"id":5235207,"uuid":"90008821-70ff-40f0-8b6b-ac2a05da0533","content":{"_uid":"49fd6f0c-b304-4e94-b6a5-94dc6b96111a","body":[],"image":"//a.storyblok.com/f/72520/3714x1308/23013c5d14/homepagebanner_nosharks_cropped.png","title":"Listing Sharks First Blog Post","content":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"image","attrs":{"alt":"","src":"//a.storyblok.com/f/72520/3714x1308/23013c5d14/homepagebanner_nosharks_cropped.png","title":null}}]},{"type":"heading","attrs":{"level":1},"content":[{"text":"We Are Listing Sharks and This is Our First Blog Post","type":"text"}]},{"type":"paragraph","content":[{"text":"We are Listing Sharks and this is our first blog post!","type":"text"}]},{"type":"paragraph","content":[{"text":"Testing to see how this whole thing works. I want to understand how to use Storyblok in order to add blog posts to Listing Sharks without having to build our own blogging engine.","type":"text"}]},{"type":"paragraph","content":[{"text":"I'm using the rich text editor to do this which mean the information here comes formatted and I render it via the Storyblok Javascript SDK which interprets a JSON object into HTML with appropriate CSS and formatting.","type":"text"}]}]},"component":"page"},"slug":"first-blog-post","full_slug":"blog/first-blog-post","sort_by_date":null,"position":0,"tag_list":[],"is_startpage":false,"parent_id":5235206,"meta_data":null,"group_id":"0f824ca2-573d-423b-b41a-ae46bdef7d60","first_published_at":"2020-01-02T20:54:07.000Z","release_id":null,"lang":"default","path":null}}
        }
    },
    computed: {
        richtext() {
            return this.text ? this.$storyapi.richTextResolver.render(this.text) : ''
        }
    }
}
</script>
```

**Comment by P4sca1** [comment]
@nelsynelz The problem is that you are calling render on the wrong object.
Try `this.$storyapi.richTextResolver.render(this.text.story.content.content)`.

**Comment by nelsynelz** [comment]
@P4sca1 that was it! I guess that was a silly mistake but I figured the api expected the entire object and would handle the parsing of each object it needed within the text object.

I noticed that I am missing formatting though, my title being bold and larger font along with line spacing seems to be missing.

I looked through the published JSON and can't find any formatting related things. 

Any hints on that subject? 

PS - Very much appreciate your help on this, thank you.

**Comment by nelsynelz** [comment]
I thought maybe it was because I wasn't getting the story from the api, however I just updated my code to call the API directly and still the same unformatted result. So I think I'm missing something else here.

```
<template>
    <div v-if="text" class="px-6 pr-10">
        <div v-html="richtext"></div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            text: null
        }
    },
    computed: {
        richtext() {
            return this.text ? this.$storyapi.richTextResolver.render(this.text.content.content) : ''
        }
    },
    async mounted() {
        try {
            const storyBlokResponse = await this.$axios.get("https://api.storyblok.com/v1/cdn/stories/?per_page=2&page=1/&token=****************************")
            this.text = storyBlokResponse.data.stories[0]
        } catch(error) {
            console.log(error)
        }
    }
}
</script>
```

**Comment by emanuelgsouza** [comment]
Hey everyone! I believe the problem is related with which type of argument the `render` method expect. So, in the last version of `storyblok-js-client`([2.3.0](https://github.com/storyblok/storyblok-js-client/releases/tag/v2.3.0)), we fix this improving the type definition and adding a warn when the render method receives a wrong argument.

We hope this is useful!
