### ISSUE TITLE
Nuxt generate static site storyblok editor not highlighting or selecting components

### ISSUE THREAD

**Issue by shadow81627** [storyblok/storyblok-nuxt#15]
I am not able to see the editor css on my static generate nuxt pages. I am able to see edited text change events but clicking content does not open the component in the editor. The below part of the documentation mentions the bridge functionality I am missing in my generated static nuxt site.

> Those HTML comments should be placed before your content-type and component representations in your website. Now all that is left to do is to add our JavaScript Bridge Script and initializing it with your draft token. This allows us to add small bits of CSS (for the borders while hovering and status border while clicked) and EventListeners to the element directly after that HTML comment. After clicking on the DOM element after the HTML comment, our JavaScript Bridge will send an iframe event to our main application, and we will open the respective content type or component in our editor.

I have a screenshot of the editor not highlighting or selecting components in the editor: https://imgur.com/a/Bf7FUCn

I have tried to add a mounted function that will enable the editor in draft mode but this only fixed my issue with the bridge events not working. 

```javascript
mounted() {
    // Check if we are in the editor mode
    if (this.$route.query._storyblok) {
      // Load the JSON from the API
      this.$storyapi
        .get('cdn/stories/home', {
          version: 'draft',
        })
        .then((res) => {
          this.story = { ...this.story, ...res.data.story };
        })
        .catch((res) => {
          if (res.response) {
            this.error({
              statusCode: res.response.status,
              message: res.response.data,
            });
          } else {
            console.error(res);
          }
        });
    }
  },
```
My attempted fix: https://github.com/shadow81627/daim/pull/177/files#diff-b19fa22add3de9cd0b98b05366479d92R40

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue!

I was not able to reproduce your issue. I used your approach (with `mounted` hook) and `generate` the dynamic routes and I'm able to enable the Live Preview in my tests.
