### ISSUE TITLE
Unpublished pages are published

### ISSUE THREAD

**Issue by mtskf** [storyblok/storyblok-nuxt#165]
With the given approach described in readme file,
all the unpublished pages are publicly accessible.

```
const story = await useStoryblok("vue", { version: "draft" });
```

Is it possible to apply `version: "published"` if not accessed from Storyblok editor?
Please advise!

**Comment by Dawntraoz** [comment]
Hi @mtskf, for sure!

One way to do that is using `useRoute().query._storyblok ? "draft" : "published"` as Daniel Kelly explains in [the Jamstack course](https://vueschool.io/lessons/only-show-published-content-on-the-live-site).

Another way is to use `.env` variables in your hosting provider, something like:
```js
{ version: process.env.STORYBLOK_VERSION }
```

I hope this resolves your query 🤗
