### ISSUE TITLE
Input event initially not firing after page load 

### ISSUE THREAD

**Issue by hamsterbacke23** [storyblok/storyblok-nuxt#17]
When opening the visual editor, re-arranging the items sometimes initially does not seem to trigger the input event, so the actual components in the visual editor would not move at all.

Only when clicking on an item in the visual editor and then trying the same thing again, everything works fine!

![moving](https://user-images.githubusercontent.com/1543397/77178180-07326200-6ac7-11ea-8fb8-53fef9b82500.gif)

**Comment by emanuelgsouza** [comment]
Hi! Did you use our [template (vue-nuxt-boilerplate)](https://github.com/storyblok/vue-nuxt-boilerplate) or create this project from scratch? We believe this could be a problem in Vue reactivity

**Comment by hamsterbacke23** [comment]
I suspected the same, but I think it's something else. I could recreate it with the boilerplate:
![vanilla](https://user-images.githubusercontent.com/1543397/77689713-6c43f700-6fa2-11ea-8e3c-dcce2a4756a5.gif)

**Comment by emanuelgsouza** [comment]
Hi! This problem was fixed in our platform. Thanks for submit this ISSUE.

**Comment by hamsterbacke23** [comment]
Nice! I can see it works now, awesome! Thank you very much!
