### ISSUE TITLE
[Feature Request] Add function to check if in edit mode

### ISSUE THREAD

**Issue by codeflorist** [storyblok/storyblok-nuxt#173]
it would be very handy to include a function to check if the user is currently in edit mode as described here: https://www.storyblok.com/faq/how-to-verify-the-preview-query-parameters-of-the-visual-editor

this way a custom implementation would not be necessary.

**Comment by Dawntraoz** [comment]
This was added to the JS SDK and will soon be updated on Vue/Nuxt SDKs. See the changes at: https://github.com/storyblok/storyblok-js/pull/247.

**Comment by Dawntraoz** [comment]
Half of this change is already included in the last merged PR https://github.com/storyblok/storyblok-nuxt/pull/323 (latest `storyblok-js` SDK). The bridge is no longer loaded outside the Visual Editor!

To automate the `draft` version, let's follow the discussion here -> https://github.com/storyblok/storyblok-nuxt/issues/174. Let's make the SDKs what people need together 🫂
