### ISSUE TITLE
[Feature Request] Automatically fetch draft version, if in edit mode

### ISSUE THREAD

**Issue by codeflorist** [storyblok/storyblok-nuxt#174]
When a user is in edit mode, the desired default behaviour is to fetch the draft version of a story. otherwise `v-editable` and the bridge-functionality are not working. An option to fetch the draft version automatically, if the user is in edit mode would be very handy.

**Comment by madebyfabian** [comment]
This is so needed. Why isn't the team aware of this? It's such a basic feature. The docs just go `version: 'draft'` in all examples, but this is completely unuseful if you are actually creating a project.

My workaround:

```ts
const getStoryblokAPIDataVersion = ({
    context = {},
    route = {}
}) => {
    const queryDefined = context?.query?._storyblok || route?.query?._storyblok,
        isDev = context?.isDev || process.env.NODE_ENV === 'development'

    let editMode = false
    if (queryDefined || isDev || window?.localStorage.getItem('_storyblok_draft_mode')) {
        if (typeof window !== 'undefined') {
            window.localStorage.setItem('_storyblok_draft_mode', '1')

            if (window.location == window.parent.location)
                window.localStorage.removeItem('_storyblok_draft_mode')
        }
        editMode = true
    }

    return editMode ? 'draft' : 'published'
}
```

**Comment by codeflorist** [comment]
i would be glad, if i could get this to work at all using generated static pages.

i'm using the composable like this:
```js
const currentStory = await useAsyncStoryblok(currentStoryPath, {
	version: useStoryblokAPIVersion(),
})
```
this works as intended in dev and built modes. but the editor displays no content at all with prerendered pages.

**Comment by Dawntraoz** [comment]
Closing this ticket since this was explained in the last part of the Ultimate Tutorial: https://www.storyblok.com/tp/create-a-preview-environment-for-your-nuxt-3-website
