### ISSUE TITLE
Api requests in components with new fetch hook?

### ISSUE THREAD

**Issue by simonhermann** [storyblok/storyblok-nuxt#18]
With [Nuxt v2.12 the new fetch() ](https://nuxtjs.org/api/pages-fetch/)was introduced, allowing for get reqests not just in pages, but in every component. This, of course, is unutterably useful combined with storyblok.
Is `context.app.$storyapi.get` usable in components inside fetch? If so, how? If no, please make it work asap!

**Comment by DominikAngerer** [comment]
Since the `context` is the same I don't see why it should not already be possible as it is the same functionality. :) 

Will have to test it – but no changes required from how I understand that feature from nuxt.

**Comment by simonhermann** [comment]
Hi Dominik :)
good to hear from you, hope you're doing well these times!
Of course I tried, but was not able to get it to work.

in vue component
```js
async fetch(context) {
    this.story = await context.app.$storyapi.get(`cdn/stories/test`, {
      version: 'draft'
    })
  }
```

Error:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Property or method "$fetchState" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

...
Cannot read property 'pending' of undefined
```

**Comment by emanuelgsouza** [comment]
Hi! @simonhermann I wasn't able to reproduce your issue

I implemented a simple example using [our boilerplate](https://github.com/storyblok/vue-nuxt-boilerplate) in codesandbox, you can [check here](https://codesandbox.io/s/test-nuxt-fetch-hook-with-storyblok-wevvl).

The component that I edited was the `components/Teaser.vue` and I using the fetch hook doing a `console.log` in both `this.$nuxt.context.app.$storyapi` and `this.$nuxt.context.$storyapi`.

And the request that I made was with the `this.$nuxt.context.app.$storyapi`.

I hope it is useful

**Comment by nimonian** [comment]
I know this is closed but I got the exact same problem, so in case anybody else is googling this: the problem is passing `context` into `fetch` with `fetch(context)`. This causes `$fetchState` to be left undefined (I think because nuxt uses the old <2.12 fetch when `context` is passed). Use `fetch()` with `this` inside fetch as mentioned above and you're good to go.
