### ISSUE TITLE
Nuxt3 with full static is still running storyblok scripts even if everything is prerendered

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-nuxt#192]
Hi! Is there currently a solution for running storyblok with nuxt3 in full static mode? Right now it is running all the calls to storyblok even if I prerender the pages, which doesn't make much sense.

![image](https://user-images.githubusercontent.com/5083273/185801674-541a3df8-c03e-4465-8f98-6d7687af3abe.png)
https://magenta-lamington-fd7f1e.netlify.app/portfolio/revolutionrace/
This example page has all the content already on it so it shouldn't have to pull anything (or even load the storyblok apis).

The only time I would think it would pull data is if I'm in the editor.

**Comment by codeflorist** [comment]
i believe this is only possible, if `storyblok-nuxt` uses the native `nuxt3`-composables for data-fetching (see here https://v3.nuxtjs.org/guide/features/data-fetching). right now it uses `axios`.

ditching `axios` for the `nuxt3`-native composables indeed seems to be the way to go for this package.

**Comment by SebbeJohansson** [comment]
@codeflorist that does seem to be true. Wrapping it in an useAsyncData does work for the calls if you use the experimental module for full static, but it still returns a ref which means that it will flash on load.

The only solution is to use a native composable or using StoryblokApi.get() inside of for example a useAsyncData with the full static experimental module.

**Comment by SebbeJohansson** [comment]
I managed to successfully do this.
Page:
```
<script setup lang="ts">

const route = useRoute();

const isPreview = route.query._storyblok && route.query._storyblok !== '' ? 'draft' : 'published';
const version = isPreview ? 'draft' : 'published';

const story = ref(await useStoryblokFetch(`blog/${route.params.slug}`, version));

onMounted(() => {
  useStoryblokBridge(story.value.id, evStory => (story.value = evStory));
});

</script>

<template>
  <div class="page blog-entry-page">
    <component
      :is="$resolveStoryBlokComponent(story)"
      v-if="story.content"
      :blok="story.content"
      :raw="story"
    />
  </div>
</template>
```
Composable:
```
import { StoryData } from '@storyblok/vue/dist';

interface Blok {
  story: StoryData;
  cv: number,
}

export const useStoryblokFetch = async (slug: string, version: string) => {
  const config = useRuntimeConfig();

  const { data: blok } = await useAsyncData(() => $fetch(`https://api.storyblok.com/v2/cdn/stories/${slug}?token=${config.public.STORYBLOK_API_TOKEN}&version=${version}`));
  return (blok.value as Blok).story;
};
```

**Comment by Dawntraoz** [comment]
This is now solved in the last release [v4.4.0](https://github.com/storyblok/storyblok-nuxt/releases/tag/v4.4.0), we included a new composable `useAsyncStoryblok` for making this easier for you  -> https://github.com/storyblok/storyblok-nuxt/pull/205.

**Comment by SebbeJohansson** [comment]
@Dawntraoz Thanks! I will look into switching from my current custom solution to this in the future!

**Comment by SebbeJohansson** [comment]
@Dawntraoz Hi again. Is it possible to make it so that this can be used outside of mounted/setup? I have a fetch functionality that I use in a NuxtRouteMiddleware. Using my custom solution works, but using useStoryblok or useAsyncStoryblok does not work. Since I have multiple sources I am pulling from it is not ideal for me to do this in a component somewhere.

![image](https://user-images.githubusercontent.com/5083273/194155619-66932a69-738a-4a74-8d36-9a2e934ba651.png)

**Comment by Dawntraoz** [comment]
@SebbeJohansson I think we have something similar reported on Discord, I will try to come up with an issue specific to this "external file" workaround so we can focus there!

**Comment by SebbeJohansson** [comment]
okay thank you!
