### ISSUE TITLE
Don't have access to this.$storyapi inside an store action

### ISSUE THREAD

**Issue by moltar** [storyblok/storyblok-nuxt#2]
I don't have `this.$storyapi` in the store action for some reason.

I see that mentioned and used in the tutorial:

https://github.com/onefriendaday/nuxtjs-multilanguage-website/blob/master/store/index.js#L21

But my `this` is only the store itself and nothing else.

**Comment by moltar** [comment]
I think it is related to this:

https://github.com/nuxt/nuxt.js/issues/457

Middleware runs only on route change, and not on the first render/page load.

**Comment by DominikAngerer** [comment]
Passing this.$storyapi to your Store actions seems like to current "best practice" with every setup. 

My team will investigate further and report back if that is different.
