### ISSUE TITLE
Empty line breaks in text area content

### ISSUE THREAD

**Issue by muhammedjenos** [storyblok/storyblok-nuxt#20]
When i render text area contents with line breaks, I get an empty line at the beginning in html. I use css (white-space: pre-line) in order to keep the between line breaks, but any help how to get rid of the empty line break that gets added in the begining?

this is the screenshot of the content in the editor
![image](https://user-images.githubusercontent.com/2158510/79794810-fbef8200-8363-11ea-937d-7b509d9b5e86.png)

This is the extra line break on the top of the content in the page
![image](https://user-images.githubusercontent.com/2158510/79794706-c3e83f00-8363-11ea-8a2d-8e66ccdbcca3.png)

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue. That's strange, because the `Textarea` field type is a simple string in the JSON. So, could you share the responsible component to render this content?

**Comment by muhammedjenos** [comment]
Hi, the text was rendering in an empty div. I checked the json and there are no line breaks visible in the data, but it does show up in the rendered source in chrome dev tools (see attached). I am not sure if there are any invisible line breaks in the json object.

![image](https://user-images.githubusercontent.com/2158510/80162755-33b92c80-85e5-11ea-8068-5518b726283d.png)

**Comment by DominikAngerer** [comment]
Feel free to drop us the API request you're performing so we can investiage further - the API key for the Content Delivery is Read-Only therefore safe to post.
