### ISSUE TITLE
Can we retrieve assets?

### ISSUE THREAD

**Issue by Lovely-Fellow** [storyblok/storyblok-nuxt#206]
Hi
I was able to get stories using useStoryblokApi  in nuxt3 project.
```const storyblokApi = useStoryblokApi();
 const { data } = await storyblokApi.get('cdn/stories/', {
 });```
 
 Can I get assets, too?
After reading following 2 articles, I've tried to replace `stories`  into `assets`. But it didn't work.
https://www.storyblok.com/docs/api/management#core-resources/stories/retrieve-multiple-stories
https://www.storyblok.com/docs/api/management#core-resources/assets/retrieve-multiple-assets

 ```const storyblokApi = useStoryblokApi();
 const { data } = await storyblokApi.get('cdn/assets/', {
 });```

Please let me know if there is an API to get assets.
Thanks.

**Comment by Dawntraoz** [comment]
Hi @Lovely-Fellow, the `useStoryblokApi` composable is calling the Content Delivery API.

In general, the SDK is only working with: 'https://api.storyblok.com/,' and what you're looking at in those links is the Management API: 'https://mapi.storyblok.com/'. You must fetch the data outside the composables provided to retrieve this information.

I hope this clarifies your query.
