### ISSUE TITLE
You can't use useStoryblok if you're not loading apiPlugin. 

### ISSUE THREAD

**Issue by rnenjoy** [storyblok/storyblok-nuxt#207]
When updating to  @storyblok/nuxt 4.4.0 i started getting this error:
You can't use useStoryblok if you're not loading apiPlugin. 

I'm using nuxt 3.

**Comment by TGlide** [comment]
This also happens to me, but in previous versions as well. Randomly editing the files where useStoryblok is called works, but the error pops up again eventually.

**Comment by rnenjoy** [comment]
When i added useApiClient: true to settings it seems to have gone away. Maybe temporarily?

**Comment by bkuri** [comment]
> When i added useApiClient: true to settings it seems to have gone away. Maybe temporarily?

I have `useApiClient: true` and I'm still getting this error.

Using @storyblok/nuxt 4.4.2

**Comment by codeflorist** [comment]
i'm getting this frequently too. restarting `yarn dev` usually fixes it. a proper fix would be much appreciated.
