### ISSUE TITLE
Usage with GraphQL

### ISSUE THREAD

**Issue by J05HI** [storyblok/storyblok-nuxt#21]
@onefriendaday @samuells 
The nuxt client uses the default REST API. It fetches all fields.
Is there an option to fetch only specific fields? If not, how can I query it with GraphQL to fetch only specific fields?
Thanks for the best CMS!

**Comment by samuells** [comment]
You are correct - it is REST API. GraphQL is a different API, which you can use and configure by yourself as it is used for different use cases.

Just check this https://www.storyblok.com/docs/graphql-api out and don't miss the GraphQL playground - `http://gapi-browser.storyblok.com?token=YOUR_TOKEN`

We are working on new documentation and better GraphQL should be part of it ... so for now is the best way look into Delivery Docs and play with playgound or you can ask us in Storyblok's Discord - https://discord.gg/Hzupt4B

**Comment by J05HI** [comment]
@samuells 
Great! Thank you so much!
Keep the good work!
