### ISSUE TITLE
Download images to assets folder

### ISSUE THREAD

**Issue by J05HI** [storyblok/storyblok-nuxt#22]
Hello @onefriendaday @samuells @emanuelgsouza @DominikAngerer 
I'm using the new [full static export](https://github.com/nuxt/nuxt.js/pull/6159) of Nuxt. It would be awesome to have an option to download images to the assets folder like in the [Gridsome Plugin](https://github.com/storyblok/gridsome-source-storyblok#downloading-images).
I need them locally to process them with webpack ([Nuxt Optimized Images](https://github.com/aceforth/nuxt-optimized-images)).

**Comment by DominikAngerer** [comment]
Hey @J05HI!

We will take a look into this!

Feel free to use our free image optimization service tho: https://www.storyblok.com/docs/image-service CDN delivery and 1TB of traffic is already included.

**Comment by J05HI** [comment]
@DominikAngerer 
Thank you very much for the fast response!
I'll take a look at the image optimization service.
