### ISSUE TITLE
(DX) make axios package part of the module

### ISSUE THREAD

**Issue by Baroshem** [storyblok/storyblok-nuxt#224]
I am not sure what is the reason for having axios as an external library because in many scenarios when I have tried the storyblok/nuxt module I needed to install axios separately.

I think, it could be improved by just shipping axios with the module or just use fetch instead.

What do you think?

**Comment by chrisnoden** [comment]
If a library is needed for the package to work, then it should be in the dependencies list. Also, I notice that if I include the latest version of axios (v1.x.x) then everything goes to pot.

**Comment by Baroshem** [comment]
@chrisnoden 

This would have been even better but I suppose that the general Storyblok JS client is using Axios under the hood so it wont be that easy to replace (not to mention that it is a breaking change for all current projects).

I also encountered the issues you mentioned with the most modern version of axios. That is why, I think it would be beneficial to freeze certain version of axios in the module so that it will be installed with it and not cause issues.

**Comment by bkuri** [comment]
Looks like `axios` needs to be included and frozen to version `0.27.2` since `v1.1.3` breaks everything as stated above.

Please consider switching to $fetch to better conform to the nuxt3 standard.

**Comment by Dawntraoz** [comment]
Hi @Baroshem, @chrisnoden and @bkuri, the axios package was added as an external library because the product team was refactoring the js-client to not use it. In the latest version, it is no longer used, we are working on updating all SDKs with the new version of the js-client, once it is included bye-bye problems, bye-bye axios 👋

I hope this clears up the problem, it was an internal debate for a long time, but now is ready!

**Comment by chrisnoden** [comment]
> Hi @Baroshem, @chrisnoden and @bkuri, the axios package was added as an external library because the product team was refactoring the js-client to not use it. In the latest version, it is no longer used, we are working on updating all SDKs with the new version of the js-client, once it is included bye-bye problems, bye-bye axios 👋
> 
> I hope this clears up the problem, it was an internal debate for a long time, but now is ready!

That's great to hear @Dawntraoz. However, right now anyone leveraging your library won't know they are required to add a pinned version of axios to their own project to make Storyblok integration work. Axios is still currently required and presumably the next version, being a breaking change by the sounds of it, will have a semver that clearly distinguishes it?

**Comment by bkuri** [comment]
IMHO this issue shouldn't be closed until ther axios package has actually been removed, which is not the case as of `@storyblok/nuxt v4.4.2`.

**Comment by Dawntraoz** [comment]
Let's add some guidelines about the axios version to be used in the v4, and once the v5 is ready without axios let's close the issue, sounds like a plan @alexjoverm @manuelschroederdev?

**Comment by alvarosabu** [comment]
@Baroshem latest version doesn't rely on Axios anymore, @Dawntraoz I will close this issue. Please feel free to open again if needed.
