### ISSUE TITLE
Multiple .get() requests

### ISSUE THREAD

**Issue by imi47** [storyblok/storyblok-nuxt#24]
I apologize if this is not the right place for this but can someone please guide me regarding sending multiple .get() requests?

I'm trying to do something like this:

context.app.$storyapi.all([requestOne, requestTwo]).then(
      context.app.$storyapi.spread((...responses) => {
        const responseOne = responses[0];
        const responseTwo = responses[1];

        console.log(responseOne, responseTwo, responesThree);
      })
    );

Thanks.

**Comment by Slackman2015** [comment]
Hello there,
you can take a look at our FAQ entry related to this topic:
https://www.storyblok.com/tp/how-to-send-multiple-requests-using-axios

**Comment by imi47** [comment]
I have seen that one but that doesn't seem like a nuxt-js implementation and it isn't using the asyncData method and the "context" parameter passed to it.

I want to know if there's a way to achieve this with context.app.$storyapi.

**Comment by imi47** [comment]
Hi @emanuelgsouza,

I have a scenario where I need to make two GET requests and I need to use the response of the first GET request in the second GET request. Can you please guide me regarding this?

**Comment by emanuelgsouza** [comment]
Hi. So, you can chain the requests. If you are using our library, you need to know that we use the axios and therefore, [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises). When we use Promises, you can chain the execution of these promises. Example from MDN documentation:

```js
doSomething()
.then(function(result) {
  return doSomethingElse(result);
})
.then(function(newResult) {
  return doThirdThing(newResult);
})
.then(function(finalResult) {
  console.log('Got the final result: ' + finalResult);
})
.catch(failureCallback)
```

I get my example above and rewrite it to make a fake scenario when I need to get the stories and after, the datasources, so:

```js
asyncData (context) {
  const options = {
    version: 'draft'
  }

  return context.app.$storyapi.getStories(options)
    .then(response => {
      // do whatever you want with response to stories
      // and return a second request, now, to get the datasources
      // when you chain the requests, you can use multiple `.then() callbacka`
      return context.app.$storyapi.get('cdn/datasources', options)
    })
    .catch(errors => {
      console.error(errors)
    })
}
```

I hope it is useful!

**Comment by imi47** [comment]
The reason I want to chain requests to begin with is that the second GET needs to be based on the first.

For example, I make the first request to fetch a story. I then get it's UUID. (I don't know the UUID to begin with. I know the slug which is in the URL. I fetch the story by `by_slug` and get it's UUID)

I then need to use this UUID in the `filter_query` of the second request.

Please guide regarding this.

**Comment by imi47** [comment]
Hi @emanuelgsouza. Thank you so much. The syntax you provided works. However, I am now facing another problem related to this: It seems like only the object of the last `return` is added to the Vue's `data` method. Therefore, the components can only access that one. Here's my code:

asyncData(context) {
    const version = context.isDev ? "draft" : "published";

    return context.app.$storyapi
      .get("cdn/stories/tag/" + context.params.tag, {
        version: version,
        by_slug: context.params.tag
      })
      .then(res => {
        let uuid = res.data.story.uuid;

        return context.app.$storyapi.get(`cdn/stories`, {
          version: version,
          starts_with: "the-hub",
          per_page: 100,
          filter_query: {
            tags: {
              exists: uuid
            }
          }
        });
      })
      .then(res => {
        return {
          posts: res.data.stories
        };
      })
      .then(res => {
        return context.app.$storyapi.get(
          "cdn/stories/tag/" + context.params.tag,
          {
            version: version,
            by_slug: context.params.tag
          }
        );
      })
      .then(res => {
        return {
          tag: res.data.story.content.name
        };
      })
      .catch(errors => {
        console.error(errors);
      });
  },

In this case, only the `tag` inside the last `then` can be used in the components and as for `posts`, I get `Property or method "posts" is not defined on the instance but referenced during render`. But if I remove the last two `then`, then `posts` becomes accessible.

Is there a solution to this?

**Comment by imi47** [comment]
This worked. I didn't know the Storyblok-nuxt syntax.

Thank you so much!

**Comment by emanuelgsouza** [comment]
You're welcome!
