### ISSUE TITLE
Storyblok-nuxt is making a GET request even on static website

### ISSUE THREAD

**Issue by imi47** [storyblok/storyblok-nuxt#25]
Hi. I'm switching between dynamic routes with nuxt-link. Those routes are being populated by Storyblok. I noticed that switching between pages was very slow, taking like 1-2 seconds. When I generated a static site with 'npm run generate', it was still very slow, even though everything was now hard-coded. I then disconnected from Internet and then It was giving me a network error in console:

`VM1200:1 GET https://api.storyblok.com/v1/cdn/stories/category/causes?version=published&cv=1591282427418&token=W7dzRkbNVkoPKhCzUNP2fwtt net::ERR_INTERNET_DISCONNECTED`

However, when I refresh the page, the hard-coded content loads properly.

So kindly guide as to **why it is too slow with nuxt-link** and **why it is making a GET request even though the content is hard-coded and how can I fix it.**

Thanks.

**Comment by imi47** [comment]
I see, thank you for your response.

**Comment by SamuelMTDavies** [comment]
> Nuxt generate currently does not do a full static generation for page transitions. As soon as you're transitioning pages you switch into a client side rendering mode. Only the first request will be static. The team behind nuxt is currently working on a full static deployment.

Hi,

Any idea if there is a PR for this and if/when it may be sorted? Are there any work arounds?
