### ISSUE TITLE
Storyblok bridges bugs with two stories loads

### ISSUE THREAD

**Issue by Joaojack** [storyblok/storyblok-nuxt#251]
Hello, i have a call to one of my stories on my index.vue page : 
```
<template>
<div v-editable="story">
  <StoryblokComponent   v-if="story.content.expertises" :blok="story.content.expertises[0]" />
</div>
</template>
<script setup>
definePageMeta({layout: 'entrance',});
  const story = await useAsyncStoryblok('home', { version: 'draft' })
</script>
```
The <expertises/> component is correctly loaded, with content, it is in my storyblok components folder.
This page calls a layout, which also uses useAsyncStoryblok for another story (header and footer): 

```
<template>
  <div id="container" class="min-h-screen flex flex-col relative w-screen">>
    <StoryblokComponent class="z-10" id="nav" ref="nav" v-editable="layout.content.header[0]" v-if="layout" :blok="layout.content.header[0]"  />
    <slot />
  </div>
  </template>
<script setup>
const layout = await useAsyncStoryblok('layout', { version: 'draft' })
</script>
```
It works fine too, content is loaded etc. BUT i can use the live edit/storyblok bridge on the website ONLY with the first story loaded, i.e the layout story. I can see the changes live when i change the header field. For the expertises one, it's not live. I have to save and reload.
If i comment out in the code my layout object and the useAsyncStoryblok of the layout, **my home object is live editable again.**
There seems to be a concurrency between storyblokbridges, and only the first story loaded is bridged.
How could i avoid that ?
Thanks

**Comment by SebbeJohansson** [comment]
I am pretty sure the Bridge only works with one story, since the visual editor doesn't support switching between stories.
What are you actually in practice trying to solve? What is the end goal?

**Comment by hubtraum** [comment]
@SebbeJohansson I assume the goal is to make the header / footer editable using the visual editor. Is there any other kind of best practice for this scenary?

I came across this today on creating my first story blok based website and also wondered what would be the best solution for components which are reused on many pages (header, footer, sidebar items, ...).

**Comment by SebbeJohansson** [comment]
@hubtraum the way i handle stuff like menus and other kinds of "config"-data is to have that editing in its own page (or without visual editor). I don't think it is possible to allow for visual editor with the bridge with multiple stories on the same page. Might be something that can be requested tho. Not sure.

**Comment by Dawntraoz** [comment]
This PR at JS SDK https://github.com/storyblok/storyblok-js/pull/254, started allowing this functionality.
