### ISSUE TITLE
Bridge does not work properly on pre built server

### ISSUE THREAD

**Issue by saschaglo** [storyblok/storyblok-nuxt#252]
I try to use the bridge in a nuxt environment. I've enabled it like the documentation states. I can also see the `storyblok__outline` classes added to each item in the visual editor.

The only difference I have is that on running the dev-environment (nuxt dev) on (https://localhost:3000) and using the URL in the the visual editor, a `storyblok__outlined` is added to the body tag of my page while it is not added when running in server mode.
In both cases (so in dev or in server mode) the bridge-specific classes to the blok-elements are added (`storyblok__outline`).

Steps to reproduce:

- Load node dependencies with your favourite package tool (i'm using yarn)
- Let run dev server (in my case: `nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem`)
- Use https://localhost:3000 in storyblok's visual editor, as soon as hovering in the visual editor, outlines are visible
- Now doing that with pre-built server, first: `nuxt build`
- `NITRO_SSL_CERT=$(cat localhost.pem) NITRO_SSL_KEY=$(cat localhost-key.pem) node .output/server/index.mjs` (to be able to let run the server also with https)
- Again, going to visual editor, hovering over visual editor does not show outlines even though they are present in DOM, just the class is not added to the body

In addition to my findings I'm puzzled about the fact that the actual logic for adding the body-class (`storyblok__outlined`) is handled in that external resource (https://app.storyblok.com/f/storyblok-v2-latest.js), so maybe this helps?!

Environment: nuxt v3-rc8
Storyblok nuxt: 4.4.1

**Comment by SebbeJohansson** [comment]
Hi. Are you able to make a minimal reproduction version of the issue? I haven't had any issues running the Bridge with the visual editor with nuxt3.

**Comment by saschaglo** [comment]
Thanks for responding. Hoped, that this is not necessary ;) I try to figure it out, because it's a project related to my work and at this time it's still confidential. But I'll figure it out somehow and provide you with infos here.

**Comment by saschaglo** [comment]
Works now with the latest version. I'll close this issue.
