### ISSUE TITLE
useStoryblok and useAsyncStoryblok doesnt support being used outside of setup because bridge needs onMounted

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-nuxt#257]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Since both `useStoryblok` and `useAsyncStoryblok` require it being used in `setup`, it is not possible to get proper routing when using app.vue instead of pages
---
The point behind me wanting to use my own routing instead of vue-router (which is what the `pages` folder in nuxt uses) is to save on bundle size. The way I need to do the route check might be a bit special since I need to support fetching from multiple CMS' in my application.
## Expected Behavior

I would expect `useStoryblok` and `useAsyncStoryblok` to work properly in for example `watchEffect` so that I can watch on route changes.

## Current Behavior

I get warnings about `onMounted` being used outside of setup, which I think is coming from the bridge.
![image](https://user-images.githubusercontent.com/5083273/208636525-eaaaa5e4-d038-47ee-bbdc-6a7820d599de.png)

## Steps to Reproduce

1. Create a new Nuxt3 project from scratch.
2. Add fetching from storyblok using `useStoryblok` or `useAsyncStoryblok` inside a watchEffect.

![image](https://user-images.githubusercontent.com/5083273/208637260-633c62d2-1377-4711-aa85-5e914bbff7a4.png)
![image](https://user-images.githubusercontent.com/5083273/208637302-62cb281d-1d7e-4ac0-8d3d-bed96e83dae4.png)
![image](https://user-images.githubusercontent.com/5083273/208637329-4243b889-b98a-44ce-9dbf-7f2ae59c7438.png)

*Full disclosure, this could all just be from me trying to do weird stuff*

**Comment by SebbeJohansson** [comment]
Here is the places where i use it in my weird project:
https://github.com/SebbeJohansson/Vrtx.ContentSystem/blob/main/composables/usePageFetch.ts#L17-L25
https://github.com/SebbeJohansson/Vrtx.ContentSystem/blob/main/composables/useStoryblokFetch.ts
https://github.com/SebbeJohansson/Vrtx.ContentSystem/blob/main/app.vue#L3

**Comment by Dawntraoz** [comment]
Hi @SebbeJohansson, you can always use `useStoryblokApi` and the `useStoryblokBridge` composables separated in this case.

For now, I will close this one, and we will work on making the module work on the server side by allowing this feature -> https://github.com/storyblok/storyblok-nuxt/issues/440
