### ISSUE TITLE
Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function

### ISSUE THREAD

**Issue by larrasu** [storyblok/storyblok-nuxt#258]
Tried a fresh install by creating a new space using the terminal code. Seems like it doesn't work on the [demo](https://stackblitz.com/edit/nuxt-3-quickstart-demo) as well.

**Comment by donni106** [comment]
i found out that it should be `import { defineNuxtConfig } from 'nuxt/config'` instead of `import { defineNuxtConfig } from 'nuxt'`

**Comment by alvarosabu** [comment]
Closed since this is probably solved after the stable release of Nuxt 3, feel free to open again if needed.
