### ISSUE TITLE
Fetch content of a story by getting it's UUID from another story without making additional GET requests

### ISSUE THREAD

**Issue by imi47** [storyblok/storyblok-nuxt#26]
Hi. Is it possible to fetch content of a story by getting it's UUID from another story _without making additinal GET requests?_

For example, I am fetching a list of posts. Each post has a UUID of it's author.

(I have made the relation as instructed here: https://www.storyblok.com/tp/how-to-build-relationships-between-2-content-types#get-the-author-of-one-post.)

Now based on the author UUID, I want to display the name of the author in the preview of each post.

Thanks.

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue! I believe that you need is the `resolve_relations` option when you fetch the posts.

You can see this described in the [Content Delivery API documentation](https://www.storyblok.com/docs/api/content-delivery?v2#examples/useful/resolve-relationships).

**Comment by imi47** [comment]
Thank you so much! I have one more question. Is it possible to apply `filter_query` based on `resolve_relations`? For example, for listing posts by a specific author, category or categories.

Thanks.

**Comment by emanuelgsouza** [comment]
Yeah, it is possible. Check the documentation about `filter_query` and take a look on [this examples](https://www.storyblok.com/docs/api/content-delivery#filter-queries/operation-in).

**Comment by imi47** [comment]
Can you please help me with this syntax?

`starts_with: "posts/",
        resolve_relations: 'author',
        filter_query: {
          author: {
            in: 'Author Name'
          }
        }`

This works when the author is a field in post with **Source** of **Self**. I am unable to do it when the author is in another story and the author field in post is set to **Stories**

Thanks and sorry for bothering you too much.

**Comment by Slackman2015** [comment]
Hello @imi47 !
Can you explain a little bit more what you want to do, please?

I can see that your example is missing the component part in the value for the field to resolve. Please take a look at my example:
https://api.storyblok.com/v1/cdn/stories/en/home?version=draft&token=5EgKInxYa31dIBnLS3UrSQtt&cv=1591726818&resolve_relations=page.option
When defining the field for resolving you need to take the name of the component the option field is embedded inside and after that comes the name of the field to solve.

**Comment by imi47** [comment]
Hi @Slackman2015 ,

Let me try to explain my scenario using this JSON:

`[
  {
    "name": "second-post",
    "created_at": "2020-06-08T08:14:57.186Z",
    "published_at": null,
    "alternates": [],
    "id": 13035009,
    "uuid": "4cec1e92-9ea2-4694-aaf2-acbbfe9fa84a",
    "content": {
      "_uid": "743836a3-b408-45d3-9704-1554a4499da2",
      "date": "2020-06-09 19:55",
      "title": "second post",
      "author": {
        "name": "Sam",
        "created_at": "2020-06-09T15:47:19.589Z",
        "published_at": null,
        "alternates": [],
        "id": 13164394,
        "uuid": "e7cbfcc4-2c0e-4ef7-b8cf-7a43a6e3053d",
        "content": {
          "Name": "Sam",
          "_uid": "fbaf18f7-aece-4502-a054-832a8b606331",
          "component": "author",
          "_editable": ""
        },
        "slug": "sam",
        "full_slug": "authors/sam",
        "sort_by_date": null,
        "position": -10,
        "tag_list": [],
        "is_startpage": false,
        "parent_id": 13032754,
        "meta_data": null,
        "group_id": "8ab2e7be-43d0-4577-abca-54ef70107b37",
        "first_published_at": null,
        "release_id": null,
        "lang": "default",
        "path": null,
        "translated_slugs": []
      },
      "filter": "home-lifestyle",
      "content": "some content",
      "component": "post",
      "filterNew": [
        {
          "_uid": "9a0c1586-095e-4578-b170-6f2f4d785e33",
          "name": "Causes",
          "slug": "causes",
          "component": "filterNew",
          "_editable": ""
        }
      ],
      "thumbnail": {
        "id": 1168091,
        "alt": null,
        "name": "",
        "focus": null,
        "title": null,
        "filename": "https://a.storyblok.com/f/85647/x/387d85ac03/arrow.svg",
        "copyright": null,
        "fieldtype": "asset"
      },
      "categories": [
        "c162e227-f134-4dcd-933b-6a6f2200f16e",
        "81ec249e-577c-4e38-8caf-a21769f32efb"
      ],
      "_editable": ""
    },
    "slug": "second-post",
    "full_slug": "posts/second-post",
    "sort_by_date": null,
    "position": -10,
    "tag_list": [],
    "is_startpage": false,
    "parent_id": 13028225,
    "meta_data": null,
    "group_id": "32f343b6-ad6b-4a7b-b6a4-9b9f4728ca20",
    "first_published_at": null,
    "release_id": null,
    "lang": "default",
    "path": null,
    "translated_slugs": []
  },
  {
    "name": "first-post",
    "created_at": "2020-06-08T07:11:28.512Z",
    "published_at": null,
    "alternates": [],
    "id": 13031351,
    "uuid": "0d1205f7-12a7-445f-a602-7824458036d6",
    "content": {
      "_uid": "cbc41d1c-a8a4-4c41-ac5a-64c0cf62d6b5",
      "date": "2020-06-15 20:59",
      "title": "first post",
      "author": {
        "name": "John Doe",
        "created_at": "2020-06-08T07:19:11.508Z",
        "published_at": null,
        "alternates": [],
        "id": 13033521,
        "uuid": "1f0d7ce2-77da-4c3e-9220-5949d6771b12",
        "content": {
          "Name": "John Doe",
          "_uid": "f281ac0f-7dc5-444c-983f-28c94a350868",
          "component": "author",
          "_editable": ""
        },
        "slug": "john-doe",
        "full_slug": "authors/john-doe",
        "sort_by_date": null,
        "position": 0,
        "tag_list": [],
        "is_startpage": false,
        "parent_id": 13032754,
        "meta_data": null,
        "group_id": "d62cf47c-fd69-40da-9aa6-8553932e4c6e",
        "first_published_at": null,
        "release_id": null,
        "lang": "default",
        "path": null,
        "translated_slugs": []
      },
      "filter": "causes",
      "content": "\n# content title\nsome content\n",
      "component": "post",
      "thumbnail": {
        "id": 1168023,
        "alt": null,
        "name": "",
        "focus": null,
        "title": null,
        "filename": "https://a.storyblok.com/f/85647/1400x1400/b642ce5d09/bridge_1_sub_render.png",
        "copyright": null,
        "fieldtype": "asset"
      },
      "categories": [
        "81ec249e-577c-4e38-8caf-a21769f32efb"
      ],
      "_editable": ""
    },
    "slug": "first-post",
    "full_slug": "posts/first-post",
    "sort_by_date": null,
    "position": 0,
    "tag_list": [],
    "is_startpage": false,
    "parent_id": 13028225,
    "meta_data": null,
    "group_id": "a86ee350-9d42-4ecf-a50f-4ca09f5b9f69",
    "first_published_at": null,
    "release_id": null,
    "lang": "default",
    "path": null,
    "translated_slugs": []
  }
]`

These are two posts fetched using 
`starts_with: "posts/",
        resolve_relations: 'post.author',`
(in `resolve_relations`, **author** works too instead of **post.author**)

 Now let's say I want to filter the posts based on the author name:

`filter_query: {
          Name: {
            in: 'John Doe'
          }
        }`

The above query will not work because `filter_query` will look at the fields immediately inside the **content** object of the fetched post, whereas the **Name** field of the author is in the **content** of the **author** field, this **content** object is inside the **content** of the post.

So, is there a way to make `filter_query` go a level deeper, inside the **content** of the **author** field, or at least immediately inside the **author** field to reach the **name** field?

**Comment by imi47** [comment]
Thanks for your help.
