### ISSUE TITLE
Library is not compatible with latest axios version

### ISSUE THREAD

**Issue by awacode21** [storyblok/storyblok-nuxt#264]
## Expected Behavior

I would storyblok-nuxt library expect to work with latest axios version

## Current Behavior

Getting a 500 page because useAsyncStoryblok fails on reading 'data' of undefined. https://stackblitz.com/edit/github-u9mbvh?file=package.json,app.vue

whereas it is working with an older axios version: https://stackblitz.com/edit/nuxt-starter-mrmnjx?file=package.json,nuxt.config.ts,app.vue

## Reproduction

https://stackblitz.com/edit/github-u9mbvh?file=package.json,app.vue

**Comment by Dawntraoz** [comment]
Hi @awacode21, thank you for reporting the issue.

As the team was removing `axios` as a dependency in our SDKs, we didn't provide a workaround for the latest version of `axios`. You can now update to the latest storyblok/nuxt and get rid of `axios` 🎉 #263, we are using the native fetch now.
