### ISSUE TITLE
Running storyblok with yarn or npm results in "You can't use useStoryblokApi if you're not loading apiPlugin." until nuxt.config.ts is resaved

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-nuxt#266]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Sporadically an issue happens where the error "You can't use useStoryblokApi if you're not loading apiPlugin." comes up when you run storyblok with nuxt3 with `yarn` or `npm`, instead of running it with `npx nuxi`. The only way to make it work again when this happens, is to resave nuxt.config.ts.
---

## Expected Behavior

I would expect that running it with `yarn` or `npm` works the same as with `npx nuxi`.

## Current Behavior

Sometimes when running with `yarn` or `npm` an error is displayed:
```
You can't use useStoryblokApi if you're not loading apiPlugin. Please provide it on StoryblokVue initialization.

storyblok-vue.mjs:628 Please initialize the Storyblok SDK before calling the renderRichText function
```
![image](https://user-images.githubusercontent.com/5083273/209570635-38ddc606-75b0-471b-91b5-de077c5181e8.png)

## Steps to Reproduce

1. Create nuxt3 project.
2. Add storyblok.
3. Run with yarn.

This issue has been mentioned on discord and in https://github.com/storyblok/storyblok-nuxt/issues/234

**Comment by CKGrafico** [comment]
+1m here, seems important.

**Comment by alvarosabu** [comment]
Do you have installed also `@storyblok/vue` package? if you do uninstall it, remove all the lock files and node_modules, also remove the `.nuxt` and run it again.

**Comment by SebbeJohansson** [comment]
@alvarosabu I do not. I do however have `@storyblok/js` and `storyblok` in the project. Not sure that matters.
I am importing "@storyblok/vue" from the installed nuxt package in a few places. Mainly to import StoryData as a type.
![image](https://user-images.githubusercontent.com/5083273/211556374-c8db248c-57f1-4aa0-acab-ece9a4d1ba8d.png)

One place that i am using it that could be the source i guess is in https://github.com/SebbeJohansson/Vrtx.ContentSystem/blob/main/composables/useStoryblokRawFetch.ts where i use `apiPlugin` to fetch stories without running the composables. `useStoryblokRawFetch` is used in `useStoryblokRawFetchDynamicRoutes` which is used in two places:
https://github.com/SebbeJohansson/Vrtx.ContentSystem/blob/main/nuxt.config.ts#L29 - to prerender routes.
https://github.com/SebbeJohansson/Vrtx.ContentSystem/blob/main/server/routes/sitemap.xml.get.ts#L6 - to create the sitemap.

Thoughts?

**Comment by alvarosabu** [comment]
The nuxt module seems to autoimport everything from the `@storyblok/vue` so you don't need it. Not even the imports are needed anymore. 

Not sure about the js one, for me revoing the vue one did the trick

**Comment by SebbeJohansson** [comment]
Do you mean that i should be able to access `apiPlugin` and `StoryData` directly from the nuxt one?
To be clear, I am NOT installing `@storyblok/vue` manually.

**Comment by SebbeJohansson** [comment]
Removing `@storyblok/js` did nothing.
![image](https://user-images.githubusercontent.com/5083273/211570016-e80a7aea-4795-47b7-8b7b-8a28e5fee7e2.png)

**Comment by Dawntraoz** [comment]
It's a problem with the Vite config that Pooya pointed out. I have the solution on the last PR #279. You can double-check locally with the branch if you want once is reviewed by my team I will merge 💜

**Comment by SebbeJohansson** [comment]
Hmm im not sure it fixed my issue actually. I just tested it.

What I did:
1. Updated @storyblok/nuxt to latest.
2. Started with nuxt dev.
3. Loaded the site in chrome.

![image](https://user-images.githubusercontent.com/5083273/212100420-497e3859-0c33-4681-b2e8-96c06562a11c.png)
Weirdly enough the data is some how still loaded. What has changed is that it is warning in different places and it also is warning me about `Please initialize the Storyblok SDK before calling the renderRichText function``.

**Comment by SebbeJohansson** [comment]
And resaving nuxt.config.ts made it work again:
![image](https://user-images.githubusercontent.com/5083273/212102022-6c1dd30f-2d40-4aba-aba1-70a927fcdbcb.png)

**Comment by Dawntraoz** [comment]
@SebbeJohansson I was proposing to test the branch from the PR, but I've already merged it. Can you check now, please? 😍

**Comment by SebbeJohansson** [comment]
@Dawntraoz I might sounds really stupid now, but I am not 100% sure on how to test the branch locally 😅

I upgrades to 5.0.1 and I can not reliably reproduce the issue anymore! So I think we can consider this fixed. Given that it has been hard to reproduce this issue over all, i am not 100% sure. But seems fine! 😁😍

**Comment by Dawntraoz** [comment]
Indeed, it should be okay now. Happy to hear that, @SebbeJohansson 💜.

Thanks to the amazing https://github.com/pi0 and your help we are good to go and fix the rest of the issues! 🎉

**Comment by SebbeJohansson** [comment]
Yea thanks, Pooya!
Sucks that you cant tag anyone anywhere on github.
