### ISSUE TITLE
Storyblok Component Name Syntax

### ISSUE THREAD

**Issue by alexrichardsweb** [storyblok/storyblok-nuxt#268]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I've been using single named blocks and as expected they work fine getting their named components from inside the `storyblok` folder, but when I get to `multiple_named` components it doesn't appear to render the component when I give it a matching underscored name (both uppercase and lowercase), I've also tried renaming the component to PascalCase and camelCase but it still doesn't register the component.

Alternatively, when I give the block a name with spaces instead of underscores, and then give the component a spaced name it actually does work.  Are underscores allowed in the names of blocks that are to be rendered as a StoryBlok component?

---

## Expected Behavior

The component is rendered when its name matches a content block with an underscored name

## Current Behavior

No component is rendered regardless of syntax

## Steps to Reproduce

1. Create a block type with an underscored name
2. Create a component inside the `storyblok` folder with a match underscored name
3. Run site locally

**Comment by Dawntraoz** [comment]
Indeed @alexrichardsweb, underscored names are not supported for blocks in <StoryblokComponent />. For that, in the [Ultimate Tutorial of Nuxt 3](https://www.storyblok.com/tp/create-and-render-blog-articles-in-storyblok-and-nuxt), you will only see names with a hyphen.

But I agree that it should be explained in the docs or added as an implementation of the dynamic component. @alexjoverm @roberto-butti @manuelschroederdev, what are your thoughts on this? Shall we include it?

**Comment by danbohea** [comment]
I lost a bunch of time today trying to discover by trial & error, what the expectations are of the "automagical" component discovery. Please document the requirements, "automagical" is entirely too vague..

**Comment by Dawntraoz** [comment]
Hi @danbohea, I think we are talking about two different things here. With hyphen naming, we mean the name given to the block within the Space in Storyblok. In the code, we always use CamelCase. You can see how we create the components in Example Space demo -> https://github.com/storyblok/storyblok-demo-default/tree/main/storyblok.

Where have you seen the word "automagical"? I would like it to be better understood in the documentation, so if you tell me where you would like to see it better explained, I will change it right away! 🫂

**Comment by danbohea** [comment]
Hi @Dawntraoz, from the root README.md:

> You can just place them on the ~/storyblok directory and will be discovered automagically

**Comment by Dawntraoz** [comment]
Thanks!! I will add a proper explanation there @danbohea, could something like this work better?

> You can place them in the ~/storyblok directory, naming them with CamelCase in your code "ExampleComponent.vue" and with a hyphen in your Storyblok space "example-component", they will be imported automatically.

**Comment by danbohea** [comment]
@Dawntraoz That would be a huge improvement to the docs, yes, thanks :)

I still can't actually get that to work reliably for blocks though:

Nested block: hero-video
Component: storyblok/HeroVideo.vue
Doesn't work

**Comment by Dawntraoz** [comment]
That, indeed, should be working fine. If it's not working, then we should check the implementation together. Can you send a link to the repo if it's open source or the code from the page where the <StoryblokComponent /> is being used? To at least try to reproduce it 🤔

**Comment by danbohea** [comment]
It's not open source. Isn't the reproduction not at least partly down to my Storyblok space config though? Surely sharing the Nuxt code is only half the story (no pun intended)?

**Comment by danbohea** [comment]
> naming them with CamelCase in your code "ExampleComponent.vue" 

@Dawntraoz That's Pascal case btw.

**Comment by Dawntraoz** [comment]
> @Dawntraoz That's Pascal case btw.

True 😂  It's late

**Comment by Dawntraoz** [comment]
> It's not open source. Isn't the reproduction at least partly down to my Storyblok space config though? Surely sharing the Nuxt code is only half the story (no pun intended)?

I want to start searching somewhere, then I can access your space by the ID, if you can provide it to me, of course.

**Comment by danbohea** [comment]
Ah great, thanks. Space ID is `196663`.

1. Go to the "home" `HomePage` story (yep, PascalCase works as a technical name on Stories).
2. You'll see a single `body` blocks field with a single nested block `hero-video`.

## Code

/storyblok/HomePage.vue (works as expected)

```js
<template>
  <div v-editable="blok">
    <StoryblokComponent v-for="blok in blok.body" :key="blok._uid" :blok="blok" />
  </div>
</template>

<script setup>
defineProps({ blok: Object })
</script>
```

/storyblok/HeroVideo.vue (nope)

```js

<template>
  <div v-editable="blok">
    <h3>Hero Video</h3>
  </div>
</template>

<script setup>
defineProps({ blok: Object })
</script>

```

**Comment by danbohea** [comment]
@Dawntraoz Thanks for the update. I'm stacked but will aim to create a reproduction for you ASAP.

**Comment by danbohea** [comment]
@Dawntraoz I've managed to recreate & resolve this now. I had 2 components with the same name:

* `/components/HeroVideo.vue`
* `/storyblok/HeroVideo.vue`

It seems that this is enough for storyblok-nuxt's "automagical" component discovery to fail. The docs do say that components need to be loaded globally, which goes some way to explaining this behaviour, but perhaps the docs could be a bit more explicit?
