### ISSUE TITLE
Errors while generating static site

### ISSUE THREAD

**Issue by imi47** [storyblok/storyblok-nuxt#27]
I'm using Storyblok-nuxt and I get some errors when I do "npm run generate" to generate a static site. Some pages go missing as a result.

I get errors such as:
`Error: socket hang up
    at connResetException (internal/errors.js:614:14)
    at TLSSocket.socketOnEnd (_http_client.js:491:23)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

`ERROR  Client network socket disconnected before secure TLS connection was established`

``Error: write EPROTO
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)``

``ERROR  read ECONNRESET
  at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)``

The errors _don't_ appear for the same pages every time. We have also tested it with a 1gbps Internet connection.

Is there anything I can do to fix this?

Thanks.

**Comment by emanuelgsouza** [comment]
Thanks for submitting this issue.

That's strange. This could be your internet connection... Could you share how are you exporting the pages? How is the project structured?

**Comment by imi47** [comment]
The `generate` object in nuxt.config.js

`generate: {
    routes: function (callback) {
      const token = `W7dzRkbNVkoPKhCzUNP2fwtt`
      const version = 'published'
      let cache_version = 0

      let toIgnore = ['home', 'en/settings']

      // other routes that are not in Storyblok with their slug.
      let routes = ['/'] // adds / directly

      // Load space and receive latest cache version key to improve performance
      axios.get(`https://api.storyblok.com/v1/cdn/spaces/me?token=${token}`).then((space_res) => {

        // timestamp of latest publish
        cache_version = space_res.data.space.version

        // Call for all Links using the Links API: https://www.storyblok.com/docs/Delivery-Api/Links
        axios.get(`https://api.storyblok.com/v1/cdn/links?token=${token}&version=${version}&cv=${cache_version}&per_page=100`).then((res) => {
          Object.keys(res.data.links).forEach((key) => {
            if (!toIgnore.includes(res.data.links[key].slug)) {
              routes.push('/' + res.data.links[key].slug)
            }
          })

          callback(null, routes)
        })
      })
    }
  }`

This is the `asyncData` method. It might give you an idea about the project structure.

asyncData(context) {
    let topics, article, content;

    return context.app.$storyapi
      .get("cdn/stories/", {
        version: context.isDev ? "draft" : "published",
        starts_with: "topic",
        sort_by: "content.order:asc"
      })
      .then(res => {
        topics = res.data.stories;

        return context.app.$storyapi.get(
          `cdn/stories/help-centre/${context.params.article}`,
          {
            version: context.isDev ? "draft" : "published",
            resolve_relations: "topic"
          }
        );
      })
      .then(res => {
        article = res.data.story;
        res.data.story.content.content
          ? (content = res.data.story.content.content)
          : (content = {});

        return context.app.$storyapi.get("cdn/stories/", {
          version: context.isDev ? "draft" : "published",
          starts_with: "help-centre",
          per_page: 4,
          filter_query: {
            topic: {
              in: res.data.story.content.topic.uuid
            }
          }
        });
      })
      .then(res => ({
        topics,
        article,
        topicName: article.content.topic.content.name,
        relatedArticles: res.data.stories.filter(e => e.uuid != article.uuid),
        content
      }));
  }

The pages that fail are _not_ the same but they always belong to the same page file in the project which is _article in help-center folder (/help-center/_article). There are other page files as well which fetch data from Storyblok but pages only fail in this one. The above code is also from /help-center/_article.

**Comment by emanuelgsouza** [comment]
Well, I was talking about your problem with the dev team and we don't believe this is a problem on our side. I recommend you look at Nuxt doc with respect to the concurrency and timeout part, maybe it's related to your problem: https://nuxtjs.org/api/configuration-generate#concurrency

**Comment by imi47** [comment]
Thank you for discussing it with the team. I managed to fix the issue by adding the following in the `build` object in nuxt.config.js:

`html: {
      minify: {
        collapseBooleanAttributes: true,
        decodeEntities: true,
        minifyCSS: false,
        minifyJS: false,
        processConditionalComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        trimCustomFragments: true,
        useShortDoctype: true
      }
    }`

This drastically sped up the process and now there are no errors.

Thanks again.
