### ISSUE TITLE
Plugin doesn't support multiple editor event handlers in one app

### ISSUE THREAD

**Issue by cyberbobs** [storyblok/storyblok-nuxt#28]
So, I'm trying to add multiple editor event handlers in Nuxt-based app. One handler is a typical hook added on `mounted` in a route:

```js
  mounted () {
    // use the bridge to listen to events
    this.$storybridge.on(['input', 'published', 'change'], (event) => {
      if (event.action === 'input') {
        if (event.story.id === this.story.id) {
          this.story.content = event.story.content
        }
      } else {
        // window.location.reload()
        this.$nuxt.$router.go({
          path: this.$nuxt.$router.currentRoute,
          force: true
        })
      }
    })
  }
```

The other one works on a layout component's `mounted` triggering the vuex mutation to update the store data (first load is done with vuex action in middleware) for header/footer components added directly in layout:

```js
  computed: {
    ...mapState(['header'])
  },
  mounted () {
    // use the bridge to listen to events
    this.$storybridge.on(['input', 'published', 'change'], (event) => {
      if (event.action === 'input') {
        if (event.story.content._uid === this.header._uid) {
          this.$store.commit('setHeader', event.story.content)
        }
      } else {
        // window.location.reload()
        this.$nuxt.$router.go({
          path: this.$nuxt.$router.currentRoute,
          force: true
        })
      }
    })
  }
```

Problem is: only the first added callback is actually called on editor events. Is there any other way to do this without losing the ability to visually edit the header item? That is not actually described or shown in the [official Nuxt guide](https://www.storyblok.com/tp/nuxt-js-multilanguage-website-tutorial#getting-global-settings-with-the-vuex-store).

**Comment by cyberbobs** [comment]
I've created a pull request with a fix for this. Please, take a look.

**Comment by f3ltron** [comment]
Hello @cyberbobs I saw you used the store to trigger change isn't it enough to dispatch what you want everywhere?.

I saw your code adding multiple cbs. I didn't try but it should work. Can you just explain maybe with a repo example what is the use-case that the store can't solve.

**Comment by alvarosabu** [comment]
@cyberbobs this is fixed here https://github.com/storyblok/storyblok-js/commit/ee50ab18cd2cc355b48d2dfef083606679203448 should be working on latest versions
