### ISSUE TITLE
Issue: v5.0.0 Outputs warning on dev/build -  WARN  Duplicated imports "useAsyncStoryblok"

### ISSUE THREAD

**Issue by oldskool73** [storyblok/storyblok-nuxt#282]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Using version 5.0.0 with Nuxt 3, when running `dev` or `build`, the following warning is output to the console:

WARN  Duplicated imports "useAsyncStoryblok", the one from "{PATH_TO_LIB}/dist/runtime/composables/useAsyncStoryblok.d.ts" has been ignored

This happens in my in my project, but can also be seen simply by cloning the repo and running `npm run demo` in the playground project.

---

## Expected Behavior

Using the library as intended should not output warnings in the conole.

## Current Behavior

Using the library as intended outputs a warning to the console.

## Steps to Reproduce

1. Clone this repo
2. Run `npm run demo`
3. Observe warning in console

![image](https://user-images.githubusercontent.com/967801/212467678-027b09c6-07b9-400d-89c8-8e3cce8b6949.png)

**Comment by Dawntraoz** [comment]
The fix is included on #283, you can now install v5.0.2.
