### ISSUE TITLE
Issue: v5.0.0 - Nuxt config type errors in TS project

### ISSUE THREAD

**Issue by oldskool73** [storyblok/storyblok-nuxt#284]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When using version 5.0.0 in a TS based project using `nuxt.config.ts`, and using the 'block' type of configuration entry (i.e a separate `storyblok: {...}` config entry, instead of inline config under the `modules`), typescript shows type errors.

If using 'strict' TS checking, this will also throw errors and prevent a dev/build.

Workaround: configure via inline `modules` config instead.

---

## Expected Behavior

Can configure via the `storyblok` configuration as normal

## Current Behavior

Can not configure via the `storyblok` configuration as normal, throws TS errors.

## Steps to Reproduce

1. Start a Nuxt 3 TS project
2. Install Version 5 of `storyblok-nuxt`
3. Attempt to add a `storyblok: {...}` configuration block to `nuxt.config.ts`, observer type errors on dev/generate/typecheck

![image](https://user-images.githubusercontent.com/967801/212527072-baa5ba67-7449-481f-b000-a11459a82d3c.png)

**Comment by SebbeJohansson** [comment]
I can confirm that the same is happening for me in 5.0.1.
![image](https://user-images.githubusercontent.com/5083273/212567525-1e0e896b-97c2-4d92-b770-521c5145f649.png)

I have a feeling that it is because of the defaults in the module:
https://github.com/storyblok/storyblok-nuxt/blob/main/lib/src/module.js#L15-L17

Might be time to make a "proper" ts conversion of the module.

**Comment by oldskool73** [comment]
Thanks for the confirm @SebbeJohansson ,  agree it's probably down to the defaults (and not providing a proper/full definition of the ModuleOptions interface)

Also agree on the 'proper ts conversion' comment. The currently included `module.d.ts` installed with this module doesn't look correct at all ... ie it doesn't look like a normal `d.ts` file, it's just the `module.mjs` file with a different extension, and shows multiple of it's on TS errors when I open it...

![image](https://user-images.githubusercontent.com/967801/212576565-8456119d-00e7-4629-b728-d3b0c6ff9834.png)

**Comment by stevengrimaldo** [comment]
Any update/movement on this?

**Comment by SebbeJohansson** [comment]
@stevengrimaldo i took another look at this, and it looks like the module would need to be properly switched to ts so that `defineNuxtModule<ModuleOptions>` works. I tried to do it, but I cant get it to run. Might be above my abilities 😅

**Comment by SebbeJohansson** [comment]
Ive only just gone and done it. Only took like 3 hours too!
#296
