### ISSUE TITLE
Live preview not updating when changes are made.

### ISSUE THREAD

**Issue by CodeThirtyTwo** [storyblok/storyblok-nuxt#297]
Having followed instructions using the useAsyncStoryblok one-liner and version: 'draft', I'm not seeing any updates being made in the Live Preview of any component within any of my pages.

Having used Storyblok with Nuxt 2 for the past few years without any issues, it's a bit concerning that now I'm running into these issues with Nuxt 3.

Just to clarify, the v-editable="blok" attribute on the components are working as expected i.e. when you click those blocks in the preview, the edit pane opens but making changes in that edit pane isn't displaying the changes.

**Comment by mattzahel** [comment]
Hey @CodeThirtyTwo , have you managed to fix this issue? My live preview updates only after saving and clicking the "refresh" button. Is this supposed to work like that?
