### ISSUE TITLE
Nested block components don't trigger onMounted

### ISSUE THREAD

**Issue by danbohea** [storyblok/storyblok-nuxt#302]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Vue's `onMounted` lifecycle hook doesn't seem to work from within a nested block component within `/storyblok/`.

Is this expected and if so what are you expected to use in its place? What am I missing here?

## Expected Behavior

`onMounted` hook should trigger when nested block component is mounted.

## Current Behavior

Code within the `onMounted` hook isn't executed.

## Steps to Reproduce

```js
<!-- /storyblok/Feature.vue -->

<template>
  <div v-editable="blok">
    <h3>Feature</h3>
  </div>
</template>

<script setup>
import { onMounted } from "vue"

defineProps({ blok: Object })

onMounted(() => {
  console.log("mounted")
})
</script>
```

You should see `mounted` in the browser console when the component mounts.

**Comment by Dawntraoz** [comment]
It should work out of the box. As I told you in the past issue, it will be nice to have a reproduction of your setup since we can't find any problems with the current use cases.

Do you need any help creating the reproduction?

**Comment by manuelschroederdev** [comment]
Hey @danbohea, I also just tested this and can confirm it works out of the box. It would indeed be great if you could share a minimal reproducible example with us so we could get to the root of the problem and provide further assistance. Thank you! 🙂

**Comment by danbohea** [comment]
@Dawntraoz & @manuelschroederdev Thanks for the update. I'm stacked but will aim to create a reproduction for you ASAP.

**Comment by manuelschroederdev** [comment]
Thank you @danbohea. 🙂
Looking forward to helping you resolve this.

**Comment by danbohea** [comment]
I've managed to recreate & resolve this now. I had 2 components with the same name:

* `/components/HeroVideo.vue`
* `/storyblok/HeroVideo.vue`

It seems that this is enough for storyblok-nuxt's "automagical" component discovery to fail. The docs do say that components need to be loaded globally, which goes some way to explaining this behaviour, but perhaps the docs could be a bit more explicit?

**Comment by Dawntraoz** [comment]
Hi @danbohea, okay, so the problem arises when you have two instances of the same component in 2 different folders?
Now I get it. I will try locally and specify that in the README and the articles, only one component could be named the same way in the whole project.

But can you explain why you needed both components to co-exist to at least understand the use case and find a proper solution for that case together?

**Comment by danbohea** [comment]
Yep, that's pretty much all you need to recreate. It's not that the component's `onMounted` hook won't fire (though this is still true), it's more that `StoryblokComponent` won't even discover/load the correct component from `/storyblok/`.

> But can you explain why you needed both components to co-exist to at least understand the use case and find a proper solution for that case together?

I'm migrating a codebase that previously wasn't integrated with Storyblok so I already have a bunch of components in `/components/`. My process is to incrementally rewrite them to integrate with Storyblok. Step 1 of this process was to copy and paste the component to `/storyblok/` (and therefore falling at the first hurdle!).

This is further compounded by Nuxt having support for multiple components with the same name in different directories (though admittedly not in the case of global components):

```
// Valid in Nuxt:
/components/foo/HelloWorld.vue
/components/bar/HelloWorld.vue
```

Ultimately I don't need both components to exist, or share the same namespace, it was just a part of a process. Knowing this limitation I can now avoid the issue altogether.

The key phrase in your docs is ["First, you need to load them globally"](https://github.com/storyblok/storyblok-nuxt#1-creating-and-linking-your-components-to-storyblok-visual-editor); Users better know exactly what this implies or they, like me, will be in for hours of wasted time wondering why it doesn't work as suggested. I don't think my use case or process are particularly unique and I'd suggest maybe making more of a point of the component naming/discovery requirements in the docs.
