### ISSUE TITLE
Editor Interaction not working

### ISSUE THREAD

**Issue by Dav3rs** [storyblok/storyblok-nuxt#312]
## Currently there is no interactivity on the editor, like clicking a text and having it instantly on the side to edit it, or inline options.

![image](https://user-images.githubusercontent.com/50024128/221377691-78626f55-2218-4aa9-8e39-3f5e586f52c7.png)

## I tried the Next.js integration and this is what I mean
![image](https://user-images.githubusercontent.com/50024128/221377884-3dbdcaee-cfac-4396-a2ab-9087879e0394.png)

**Comment by alvarosabu** [comment]
Hi, @Dav3rs thanks for reaching out. I have some questions to try to understand this one better:

1. Are you using `v-editable` in the component you want to edit?
2. Which version of: Nuxt, Vue and this SDK are you using?
3. Do you have a reproduction link?

Thanks in advance

**Comment by Dav3rs** [comment]
I'm using the latest everything, just create a new project with `npx @storyblok/create-demo@latest --key XXXXXXXXXXXXXX --region us-east-1` and it doesn't have interactivity, I completed the tutorial entirely without it.

**Comment by Dawntraoz** [comment]
Hi @Dav3rs, let's try to solve this together!

I created a new space on the US servers, created the project with the command, added the certificate locally, removed the comments from the API Region, and added the https://localhost:3000/ with Real Path to '/' in the space. And the interactivity is working as expected.

Can you check if there are multiple`useAsyncStoryblok` or `useStoryblok` in your code being used on the same page? As they include the bridge, they should be used only 1 per route. In addition, what @alvarosabu said will help us to know what it's happening to you (the reproduction link will be so helpful!). Thanks in advance Dave!

**Comment by Dav3rs** [comment]
Okay, I'm using the "Local Editor", it doesn't work there. I just tried the "Online Editor", interactivity works there fine. So, I think it's related to the local editor only.

**Comment by Dawntraoz** [comment]
And in the Next.js integration that you tried worked locally too? I will ask my team about the "Local Editor" in the meantime.

**Comment by Dav3rs** [comment]
Yes indeed! The local editor worked for Next.js.

**Comment by Dawntraoz** [comment]
Hi @Dav3rs, the fix was introduced in our demo environment: https://github.com/storyblok/storyblok-create-demo/commit/216d5a761b8950cc014a649626e5f64bb6dd3cdd, the project was lacking the `customParent` option needed to work locally.

You can add it to your instance or create one with the command again 💜
