### ISSUE TITLE
Better error handling on useAsyncStoryblok

### ISSUE THREAD

**Issue by alvarosabu** [storyblok/storyblok-nuxt#317]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Improve the error handling on the composable `useAsyncStoryblok` to provide the user with more accurate information.

---

**Comment by SebbeJohansson** [comment]
Maybe it shouldnt use the internal nuxt3 one... maybe that was a misstake.

**Comment by Dawntraoz** [comment]
This issue is already being discussed at https://github.com/storyblok/storyblok-nuxt/issues/329

**Comment by Dawntraoz** [comment]
We will pass the error to the call directly. https://github.com/storyblok/storyblok-nuxt/pull/398

**Comment by SebbeJohansson** [comment]
@Dawntraoz Interesting changes. Especially the change to useState as the suggested way to do SSR. Has this been tested for generating static pages during build/generate?

**Comment by SebbeJohansson** [comment]
@Dawntraoz amazing! Thanks for all the hard work 🥳
