### ISSUE TITLE
Custom components can't be set via renderRichText resolver

### ISSUE THREAD

**Issue by sumerokr** [storyblok/storyblok-nuxt#320]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

Documentation says
> You can also set a custom Schema and component resolver by passing the options as the second parameter of the renderRichText function.
```
renderRichText(props.blok.articleContent, {
  schema: mySchema,
  resolver: (component, blok) => {
    switch (component) {
      case "my-custom-component":
        return `<div class="my-component-class">${blok.text}</div>`;
      default:
        return "Resolver not defined";
    }
  }
})
```

## Current Behavior

I have tried a few different combinations (with/without Schema) to make it work, but had no luck. The idea is pretty simple — I want to replace some generic tags (e.g. `<p>`) with my own custom components during rich text rendering. Or maybe I didn't get the purpose of renderRichText and its resolver?

## Steps to Reproduce

Here is a reproduction link.
https://stackblitz.com/edit/github-5bwqah?file=pages/index.vue

**Comment by joezimjs** [comment]
This isn't what the component resolver is for. The component resolver is for when you embed a Storyblok component inside of a rich text field, such as the Feature component in the screenshot below.

![image](https://user-images.githubusercontent.com/1313898/228129145-2a2312b0-1aa0-4378-b14b-1cd3e26784d3.png)

**Comment by sumerokr** [comment]
@joezimjs thanks for the clarification! That was not that obvious :thinking: . I'll give it a try!
