### ISSUE TITLE
Error in US spaces using resolve_relations + useStoryblokBridge

### ISSUE THREAD

**Issue by Dav3rs** [storyblok/storyblok-nuxt#326]
## I have been experiencing errors on the editor while using resolveRelations in the US space.

How to reproduce:

1- Create an space on US.
2- Create a global component, I followed the guide for it, (but it also happened while following the nuxt tutorial, I wasn't able to work any more on the home page that hold the popular articles component, and just moved forward with other pages)
3- **See the image below:** After selecting a reference an api request to `https://app.storyblok.com/v1/cdn/stories` will break the page with a 401 unautorized. 
- On the local editor it will try to redirect to a route that doesn't exists `https://localhost:3000/#!/logout`
- On the online editor it will show the warning about loosing updates, preventing the navigation to the logout instead (choosing discard will logout).
- This redirect behavior will fire after any update on the page if a reference is present.

4- Disabling the `resolveRelations` property on the bridgeOptions will stop triggering the api call, but also break the reference after any update on the page, so... not a solution, I just point there for looking at.

![image](https://user-images.githubusercontent.com/50024128/224442861-4557027f-515f-4e81-8aba-4025ffab4e47.png)

## I replicated on EU spaces an it doesn't break.

![image](https://user-images.githubusercontent.com/50024128/224440648-1a01fc82-ce01-4eb6-a5e6-39f0b62ce2ae.png)

## I suspected of US because the example space works fine.

![image](https://user-images.githubusercontent.com/50024128/224441106-e2085bfa-fd5f-4892-903b-245775e17fa0.png)

## So, since the same code works in EU I would discard an issue in the `useStoryblokBridge` options and suspect that is a US region problem.

**Comment by Dav3rs** [comment]
I just found the same on the react integration

https://github.com/storyblok/storyblok-react/issues/361

**Comment by RyanMulready** [comment]
+1 we are also having this issue and can replicate it working correctly in `eu` but not in `us` spaces.

**Comment by alexjoverm** [comment]
Hey all, this was fixed at `storyblok-js-client` level (the baseline library). If you update to latest version it should be fixed, feel free to reopen if it's not the case
