### ISSUE TITLE
How to use setComponentResolver?

### ISSUE THREAD

**Issue by reinoldus** [storyblok/storyblok-nuxt#34]
Where would be the best part to add "setComponentResolver" for the RTE?

I've tried adding it before I need it, but it doesn't seem to get picked up:

      this.$storyapi.setComponentResolver((component, blok) => {
        console.log("?!")
        return `<component :blok='${JSON.stringify(blok)}'
                     is="${component}"></component>`
      })

**Comment by f3ltron** [comment]
Hello :). I have written an article about this. I think it will be able to help you for your questions. As soon as I have news from storyblok It will help you for sure.

**Comment by madebyfabian** [comment]
For everyone searching on this one, here is how to do it: https://www.storyblok.com/faq/how-to-render-richtext-nuxt

**Comment by MvdLanden** [comment]
@chrisnoden Did you ever figure out how to resolve nested components inside a richtext field?

**Comment by chrisnoden** [comment]
> @chrisnoden Did you ever figure out how to resolve nested components inside a richtext field?

Unfortunately not. For now I've had to avoid allowing nested blocks inside a richtext.

I see they've recently made some changes to the Rich Text API in `4.3.0`. I'll endeavour to find time to test the nested components again.

**Comment by Dawntraoz** [comment]
The FAQ is now updated for the Nuxt 3 implementation: https://www.storyblok.com/faq/how-to-render-richtext-nuxt
