### ISSUE TITLE
useAsyncStoryblok doesnt seem to return any content at all in built/generated mode when previewing a page

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-nuxt#394]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When previewing a page, it seems like `useAsyncStoryblok` doesn't return any data in generated/built mode
---

## Expected Behavior

I expect the composable to return data properly.

## Current Behavior

No data is returned:
![image](https://user-images.githubusercontent.com/5083273/235476608-fb91b59b-5e5e-4fba-af3c-7fe0eff9af2f.png)

Fetch itself does seem to return data.
![image](https://user-images.githubusercontent.com/5083273/235476701-5c33842d-612e-42e6-8e8b-94e965897545.png)

## Steps to Reproduce

1. Create a nuxt3 application.
2. Use `useAsyncStoryblok` to fetch storyblok data.
3. Use `.then((response))` to handle data.
4. Print return data.

**Comment by SebbeJohansson** [comment]
@Dawntraoz figured i would report the issue in a separate one rather than talk about it in the error handling or similar issue 😉🥳

**Comment by Dawntraoz** [comment]
Hi @SebbeJohansson, can you please send me your code snippet for that call? Why are you using `.then` instead of assigning the reference with the top-level `await`?

**Comment by SebbeJohansson** [comment]
@Dawntraoz Sorry cant grab any code right now. I guess its just a preference. not sure there is a specific reason.

**Comment by SebbeJohansson** [comment]
This is is the only thing i can find right now.
Where I am working on this: https://github.com/SebbeJohansson/vrtx.ContentSystem/blob/main/composables/useStoryblokFetch.ts#L12-L47
Current changes I've done after I noticed this and instead added my own fetching pretty much completely: https://github.com/SebbeJohansson/vrtx.ContentSystem/commit/9600cc882b73f54ffd07534756975ee36020ffa2

I can probably make a minimum repro of this issue if needed.

**Comment by SebbeJohansson** [comment]
@Dawntraoz let me known if you need a more proper reproduction!
