### ISSUE TITLE
Text color is used as text background when RenderRichText() is used

### ISSUE THREAD

**Issue by angh0r** [storyblok/storyblok-nuxt#401]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When rendering a page with Rich Text content, color used for text color is used as text background instead.

---

## Expected Behavior

Color should be applied to text not background

## Current Behavior

Text color is applied to text background

## Steps to Reproduce

1) add rich text field 
2) add renderRichText in your component that uses that field data
3) change color of text.
4) color of text background will be changed

![image](https://user-images.githubusercontent.com/17060750/236451587-dd5c0a03-3410-4e89-9528-bf64eccd6c77.png)

**Comment by alvarosabu** [comment]
Hi @angh0r thanks for reporting the issue. Indeed several users reported this and it was fixed on https://github.com/storyblok/storyblok-js-client/pull/520 on the https://github.com/storyblok/storyblok-js-client repo.

We're currently waiting to update the versions on the SDKs to have this fixed as soon as possible. I will update this ticket when is done.

Thanks

**Comment by angh0r** [comment]
Just pulled latest build - now color text looks OK :)
