### ISSUE TITLE
bug: No Loader is configured after install storyblok error

### ISSUE THREAD

**Issue by chstappert** [storyblok/storyblok-nuxt#438]
### Describe the issue you're facing

I got the following error after installing `@storyblok/nuxt`:

```
✘ [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/fsevents@2.3.2/node_modules/fsevents/fsevents.node

    node_modules/.pnpm/fsevents@2.3.2/node_modules/fsevents/fsevents.js:13:23:
      13 │ const Native = require("./fsevents.node");
```

One possible solution is to exclude `fsevents` from the vite Config, but it may not be a permanent fix. Here's how to do it:

```
vite: {
    optimizeDeps: {
      exclude: ['fsevents'] }
    },
```

### Reproduction

need reproduction

### Steps to reproduce

1. install pnpm @storyblok/nuxt
2. setup config with accessToken
3. Run server
4. face error

### System Info

```shell
Nodejs 18,     
"@storyblok/nuxt": "^5.4.9"
"nuxt": "^3.4.1",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
Adding the fsevents by default in the plugin till Vite have a solution https://github.com/storyblok/storyblok-nuxt/pull/398/commits/63d8f69a03eff9c3297e33e1678b22ec44da145c
