### ISSUE TITLE
How to migrate to the new version?

### ISSUE THREAD

**Issue by reinoldus** [storyblok/storyblok-nuxt#47]
There is no guide on how to migrate.

This guide refers to an outdated github-repo: https://www.storyblok.com/tp/nuxt-js-multilanguage-website-tutorial#setting-up-the-environment

Where is this magical StoryblokBridge() coming from?

```
  mounted () {
    this.$storybridge(() => {
      const storyblokInstance = new StoryblokBridge()

      storyblokInstance.on(['input', 'published', 'change'], (event) => {
        if (event.action == 'input') {
          if (event.story.id === this.story.id) {
            this.story.content = event.story.content
          }
        } else {
          window.location.reload()
        }
      })
    }, (error) => {
      console.error(error)
    })
  },

```

**Comment by lukas-a-brand** [comment]
if it is only about linting complaining about StoryblokBridge you might have a solution in doing it like
```new window.StoryblokBridge()```

**Comment by reinoldus** [comment]
Thank you that helped!

A one paragraph migration guide would have been helpful though

**Comment by alvarosabu** [comment]
I will close this due to inactivity. If you feel it should be reopened and it's still a pain point, feel free to re-open
