### ISSUE TITLE
How to correctly use `useAsyncStoryblok` inside a composable?

### ISSUE THREAD

**Issue by stefanobartoletti** [storyblok/storyblok-nuxt#485]
In my current setup, I have a special story inside Storyblok editor called `site-config` that stores all info not directly related to a single webpage but as general info for my entire website, like header and footer info, settings and so on.

At the moment, I'm using this to retrive this Story inside every Vue file where I need to access the relevant data

```js
const siteConfig = await useAsyncStoryblok('config/site-config', {
  version: 'draft',
  resolve_links: 'url',
})
const config = siteConfig.value.content
```

But it is not really handy and even not too correct to duplicate code like this, so I'm willing to create a custom composable and ue in wherever I need this data.

I tried to create something like this

```js
export const useSiteConfig = () => {
  const siteConfig = await useAsyncStoryblok('config/site-config', {
    version: 'draft',
    resolve_links: 'url',
  })
  const config = siteConfig.value.content
  
  return config
};
```

then in my templates using `const config = useSiteConfig()`, but it's not working.

First of all, to address the problem that 'await' expressions are only allowed within async functions and at the top levels of modules, I edited my composable like this

```js
export const useSiteConfig = async () => {
  const siteConfig = await useAsyncStoryblok('config/site-config', {
    version: 'draft',
    resolve_links: 'url',
  })
  const config = siteConfig.value.content
  
  return config
};
```

But even now the data is not retrieved correctly, and Nuxt keeps giving me a 500 error.

Am I doing something wrong? How can I use `useAsyncStoryblok` inside another composable?

**Comment by Dawntraoz** [comment]
Indeed @stefanobartoletti, you shouldn't use the composables outside the setup. Why? Because we are using the `onMounted` lifecycle hook to initialize the bridge.

If you want to externalize the API call, you can do it using the other approach, having the `useStoryblokApi` in your wrapper function and the `useStoryblokBridge` on the pages setup itself, like in the short-hand equivalent: https://github.com/storyblok/storyblok-nuxt/blob/main/README.md#composition-api

**Comment by stefanobartoletti** [comment]
Thanks for your reply @Dawntraoz !

Using `useStoryblodBridge` in the context of what I need to do is mandatory, or using only `useStoryblokApi` could be sufficient?

Anyway, thanks for the clarifications 🙏🏻

**Comment by Dawntraoz** [comment]
In the composable you're creating, you will use only `useStoryblokApi`, indeed!

> The bridge should be only added on the page context, where you want to allow RealTime Editing, and it's optional.
