### ISSUE TITLE
Routing not working properly (page is redirecting wrong on page refresh / initial page load)

### ISSUE THREAD

**Issue by silberundeis** [storyblok/storyblok-nuxt#487]
After trying out every possible solution i could find, i finally opened an issue in hope for someone to help me figure out what i am doing wrong. (or if it is a bug)

**Setup:**
```
"@marvr/storyblok-rich-text-vue-renderer": "3.2.1",
[...]
"@nuxt/vite-builder": "3.5.3",
[...]
"@pinia/nuxt": "0.4.11",
[...]
"@storyblok/nuxt": "^5.5.2",
[...]
"@vueuse/nuxt": "10.1.2",
[...]
"nuxt": "^3.5.3",
"pinia": "2.1.3",
[...]
"storyblok-js-client": "^5.10.6",
[...]
```

**Current behavior:**
Running everything locally via `npm run dev`works as expected. 
Running `npx serve .output/public` or deploying it to my server causes the issues. 

If i open a page (e.g. ''/projects"), the page shows a few milliseconds and redirects to an empty page immediately (with just my global modules showing). If i click on a link from that empty page (e.g. "/contact") everything works properly. So it only occurs if i initially load a page. 

Im not sure what causes this. Since there is no trailing slash in the URL opened, it shouldn't do anything.

**Expected behavior:**
TrailingSlash gets remove from url and the page shows correctly.

**Steps to reproduce:**
**nuxt.config.js**
```
router: {
    trailingSlash: false,
    middleware: 'trailingSlash.global',
  }, 
```

**middleware/trailingSlash.global.ts**
```
import { defineNuxtRouteMiddleware, navigateTo } from '#app';

export default defineNuxtRouteMiddleware((to, from) => {
  if (to.path !== '/' && to.path.endsWith('/')) {
    const { path, query, hash } = to;
    const nextPath = path.replace(/\/+$/, '') || '/';
    const nextRoute = { path: nextPath, query, hash };
    return navigateTo(nextRoute, { redirectCode: 301 });
  }
});

```

Maybe this is not a storyblok-nuxt thing but a nuxt issues itself.

**EDIT:**

The routing seems to be working  somehow. Unfortunately the dynamic content fetched via `useAsyncStoryblok` isnt shown. (or actually disappears after half a second)

**Comment by Dawntraoz** [comment]
Hi @silberundeis, indeed, as you pointed out, this issue is not related to Storyblok, is a Nuxt/deployment behavior. Please check this article or some reference on what you mentioned: https://dev.to/mornir/nuxt-netlify-and-the-trailing-slash-3gge.

And please, just to be able to assign a person and time for the issues on the SDKs, use the **SDK bug or FR templates** next time. It will help us a lot with the info we need to deliver proper solutions 🤗
