### ISSUE TITLE
docs: update examples

### ISSUE THREAD

**Issue by larzon83** [storyblok/storyblok-nuxt#52]
The examples are missing how to get `StoryblokBridge`. From the [docs](https://www.storyblok.com/docs/Guides/storyblok-latest-js#usage-of-storyblokbridge):

```js
const { StoryblokBridge } = window
```

I also get _"you are not in edit mode"_ console errors while on localhost. To silence this I wrapped everything with this (also mentioned in the [docs](https://www.storyblok.com/docs/Guides/storyblok-latest-js#checking-if-you-are-inside-of-storyblok)):

```js
if (window.location.search.includes('_storyblok')) { //... }
```

There is also a small typo. Should be `if (event.action === 'input')` with three `=` instead of just two.

Complete example:

```js
export default {
  mounted () {
    if (window.location.search.includes('_storyblok')) {
      this.$storybridge(() => {
        const { StoryblokBridge } = window
        const storyblokInstance = new StoryblokBridge()

        storyblokInstance.on(['input', 'published', 'change'], (event) => {
          if (event.action === 'input') {
            if (event.story.id === this.story.id) {
              this.story.content = event.story.content
            }
          } else {
            this.$nuxt.$router.go({
              path: this.$nuxt.$router.currentRoute,
              force: true,
            })
          }
        })
      }, (error) => {
        console.error(error)
      })
    }
  }
}
```

**Comment by katerlouis** [comment]
I'm also confused on where `StoryblokBridge` comes from or how it's supposed to work? I guess it's just available on app.storyblok.com where I edit my content?

**Comment by katerlouis** [comment]
I now get where my confusion comes from: `this.$storybridge()` is supposed to add a script tag for the StoryblokBridge v2 library, but that's not happening for me on localhost, therefore the callback never gets called. The network tab doesn't show the script loaded and the DOM also shows no script-tag. 

I have no idea why, though :O 
I've read the source code and don't see why `loadScript` isn't doing what it's supposed to :D

**Comment by alvarosabu** [comment]
Hi, @larzon83 and @katerlouis sorry that the answer took too long to arrive.

Currently, there is a [useStoryblokBridge](https://github.com/storyblok/storyblok-nuxt#usestoryblokbridgestoryid-callback-bridgeoptions) that would cover all your needs.

If it doesn't work for you please feel free to reopen

**Comment by katerlouis** [comment]
And what about nuxt2? @alvarosabu
