### ISSUE TITLE
fetch is not defined and Cannot find name 'toIgnore'

### ISSUE THREAD

**Issue by ghost** [storyblok/storyblok-nuxt#525]
### Describe the issue you're facing

[How to generate routes for Nuxt with Storyblok](https://www.storyblok.com/faq/how-to-generate-routes-for-nuxt-js-using-storyblok).

I'm trying to follow the above tutorial, but it's not working locally. This makes it quite hard to debug. Especially because `toIgnore` doesn't exist in the code in `fetchStories.ts`.

Could you please create a better and working example?

### Reproduction

/

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 2.22 GB / 15.41 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1


"nuxt": "^3.6.3",
"@storyblok/nuxt": "^5.5.2",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
I added to the docs the constant that was missing, `toIgnore` was just a constant variable for the slugs you want to ignore (it was added in the Nuxt 2 one):
```js
const toIgnore = ['home', 'en/settings']
```
And a note for the Node version required to work with native `fetch` 🤗

Sorry for the inconvenience.
