### ISSUE TITLE
How to show content changes in standalone tab / preview mode

### ISSUE THREAD

**Issue by katerlouis** [storyblok/storyblok-nuxt#53]
I'm using `localhost:3000` as my preview url.

The visual inside the storyblok editor tab works as expected and injects the new json on every input. That's nice!

But when I click the preview Icon inside of storyblok to get the full page in it's own tab, the changes are not reflected in this new tab. Even when I hit `save` in the editor and open the preview again, the changes are not reflected. 

In the libraries source-code I found a check for `window.location === window.parent.location` followed by a return, if true

Doesn't that limit the update capabilities to be only present in the iframe?

**Comment by alvarosabu** [comment]
I will close this due to inactivity. If you feel it should be reopened and it's still a pain point, feel free to re-open
