### ISSUE TITLE
Installation instructions are incorrect

### ISSUE THREAD

**Issue by cmorrow-rv** [storyblok/storyblok-nuxt#58]
Installation are incorrect: nuxt-storyblok should be "storyblok-nuxt";

I'm guessing repo was renamed at some point

Currently instruction are:
```
npm install --save-dev nuxt-storyblok axios
// yarn add nuxt-storyblok axios
```

Should be:
```
npm install --save-dev storyblok-nuxt axios
// yarn add -D storyblok-nuxt axios
```

**Comment by bzelba** [comment]
This really helped a lot! Pulled my hair out why this package did not install, thx!

**Comment by pascalwengerter** [comment]
@cmorrow-rv could you point out where you found this? Can't see it within this repo, perhaps it has been fixed in the meantime? ;)

**Comment by alvarosabu** [comment]
Hi @cmorrow-rv I will close this since v.5.0.0 is no longer using Axios. Thanks
