### ISSUE TITLE
Refetch data after changing page parameter

### ISSUE THREAD

**Issue by stijns96** [storyblok/storyblok-nuxt#616]
### Description

Refetch data when page parameter has been changes.

```vue
<script setup>
  const page = ref(1)
  
  const { data } = await storyblokApi.get('cdn/stories', {
    version: 'draft',
    starts_with: 'blog',
    is_startpage: false,
    per_page: 1,
    page: page.value,
  })
  
  const articles = ref(data.stories)
</script>

<template>
  <div>
    <button v-for="index in 5" :key="index" @click="page = index">
      {{ index }}
    </button>
  </div>
</template>
```

### Suggested solution or improvement

#

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
If you like or use `VueUse` in your project, you can use the [`computedAsync`](https://vueuse.org/core/computedAsync/). If not, using a [watcher](https://vuejs.org/api/reactivity-core.html#watch) should work too.
