### ISSUE TITLE
Nuxt 3.4.0 - 3.8.2 + nitro 2.8.0 bug | [ERROR] No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"

### ISSUE THREAD

**Issue by lammerfalcon** [storyblok/storyblok-nuxt#660]
### Describe the issue you're facing

Error when starting project (dev/build)
```
`✘ [ERROR] No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"

    node_modules/.pnpm/globby@14.0.0/node_modules/globby/ignore.js:8:8:
      8 │ import {toPath} from 'unicorn-magic';
        ╵         ~~~~~~

✘ [ERROR] No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"

    node_modules/.pnpm/globby@14.0.0/node_modules/globby/index.js:7:8:
      7 │ import {toPath} from 'unicorn-magic';
        ╵         ~~~~~~


 ERROR  [unhandledRejection] Build failed with 2 errors:                                                                11:53:08
node_modules/.pnpm/globby@14.0.0/node_modules/globby/ignore.js:8:8: ERROR: No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"
node_modules/.pnpm/globby@14.0.0/node_modules/globby/index.js:7:8: ERROR: No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"

  node_modules/.pnpm/globby@14.0.0/node_modules/globby/ignore.js:8:8: ERROR: No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"
  node_modules/.pnpm/globby@14.0.0/node_modules/globby/index.js:7:8: ERROR: No matching export in "node_modules/.pnpm/unicorn-magic@0.1.0/node_modules/unicorn-magic/default.js" for import "toPath"
  at failureErrorWithLog (node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
  at node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
  at node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

```
nuxt 3 issues topic 
https://github.com/nuxt/nuxt/issues/24387

### Reproduction

https://stackblitz.com/~/github.com/jordypereira/nuxt-bug-globby-repro

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 284.17 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.6.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.13 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by stefanobartoletti** [comment]
I was the one to open the original issue on the Nuxt repository (as I was convinced that it was a problem on that part).

To provide a little more context, this problem occurred only after upgrading to Nuxt `3.8.2` with the suggested method `nuxi upgrade --force`, that deletes the lockfile and rebuild it (thus, resolving again all the dependencies versions).

My guess is that the first step should be to try to update all Nuxt related dependencies on this module too (especially `nuxt`, `@nuxt/kit` and `nitropack`, that directly depend on `globby` and `unicorn-magic`, where the actual issue originates), and see if that solves the problem.

**Comment by lammerfalcon** [comment]
I found a quick solution
We need to downgrade nitro to 2.7 version... to do it - add following code into package.json
"overrides": {
"nitropack": "2.7.0"
}

**Comment by narr07** [comment]
> I found a quick solution We need to downgrade nitro to 2.7 version... to do it - add following code into package.json "overrides": { "nitropack": "2.7.0" }

Still error with this
`{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.8.2",
    "vue": "^3.3.8",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@nuxt/ui": "^2.10.0",
    "@storyblok/nuxt": "^5.7.7"
  },
  "overrides": {
    "nitropack": "2.7.0"
  }
}
`

**Comment by lammerfalcon** [comment]
> > I found a quick solution We need to downgrade nitro to 2.7 version... to do it - add following code into package.json "overrides": { "nitropack": "2.7.0" }
> 
> Still error with this `{ "name": "nuxt-app", "private": true, "type": "module", "scripts": { "build": "nuxt build", "dev": "nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem", "generate": "nuxt generate", "preview": "nuxt preview", "postinstall": "nuxt prepare" }, "devDependencies": { "@nuxt/devtools": "latest", "nuxt": "^3.8.2", "vue": "^3.3.8", "vue-router": "^4.2.5" }, "dependencies": { "@nuxt/ui": "^2.10.0", "@storyblok/nuxt": "^5.7.7" }, "overrides": { "nitropack": "2.7.0" } } `

you can try fixed nuxt version 3.8.0(i think 3.8.2 doesnt work with 2.7.0)  and override niropack by 2.7.0 version

**Comment by stefanobartoletti** [comment]
Thanks for your workarounds,  but I'm not really keen on forcing the use of outdated dependencies, it may lead to other unexpected problems, even without them being so obvious.

We have now a PR by Daniel Roe himself that should fix this: #662. As soon as @Dawntraoz or @alvarosabu have a moment to review and merge the PR, we can see if that is enough to solve this.

**Comment by Dawntraoz** [comment]
Thanks for reporting guys @lammerfalcon, @stefanobartoletti & @narr07! Checking the amazing @danielroe PR and merge coming your way!

**Comment by Dawntraoz** [comment]
The PR has already been merged and published! Please check it out in your own projects for any edge cases, I've already checked a couple of mine and works like a charm again 🚀

**Comment by stefanobartoletti** [comment]
Thanks for taking care of this @Dawntraoz !
