### ISSUE TITLE
cache not working anymore since v6.0.0

### ISSUE THREAD

**Issue by codeflorist** [storyblok/storyblok-nuxt#687]
### Describe the issue you're facing

i'm using this config:
```js
	storyblok: {
		accessToken: '...',
		apiOptions: {
			cache: { type: 'memory' },
		},
	},
```

cache was working with v5.7.10, but since upgrading to v6.0.0 it does not seem to work anymore.

static site generation takes considerably longer because of that.

### Reproduction

none

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 PRO 4750GE with Radeon Graphics
    Memory: 1.55 GB / 15.42 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by matthewbecker1990** [comment]
@codeflorist Could this issue be causing my _payload files to be missing the data from useAsyncStoryblok? I could have sworn this data was in there a few days ago before I upgraded tom 6.0.0.

**Comment by Dawntraoz** [comment]
Hi @codeflorist, let me investigate what happened after the latest JS SDK changes to see if this has been solved in the latest release (since there were some changes this week about caching, actually).

Did you check already with 6.0.1? Let me know if it solves it, in the meantime, I will ask the SDKs team. Thanks for reporting it!

**Comment by Dawntraoz** [comment]
Hi @codeflorist, after checking the code and with the team, nothing has changed that should affect your option for `cache` 🤔

To help you find the issue can you provide a reproducible example? What's the difference in the static generation timing?
If you prefer to show this during a call let me know and I can arrange one.

**Comment by codeflorist** [comment]
@Dawntraoz that indeed sounds like a very elusive bug. 😬 many thanks for your efforts!

**Comment by alvarosabu** [comment]
Hi @codeflorist do you think this could be related to https://github.com/storyblok/storyblok-js-client/issues/823 ? If so we just merged a potential fix, we need to wait for the version bump to reach the nuxt module

**Comment by codeflorist** [comment]
Hay @alvarosabu, i think this was already fixed some time in the past, as i was using most current versions recently and did not encounter the problems anymore. Thanks for the heads-up nonetheless!
