### ISSUE TITLE
Module breaks types for auto imported components

### ISSUE THREAD

**Issue by jonathanwilke** [storyblok/storyblok-nuxt#688]
### Describe the issue you're facing

When we activate the module in our app, it breaks the type completion for auto imported components. When we deactivate the module, everything works as expected.

https://github.com/storyblok/storyblok-nuxt/assets/1453455/2506078a-4031-49e0-a593-ecd5180c7671

### Reproduction

See video

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 206.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v18.15.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by alvarosabu** [comment]
Hi @jonathanwilke thanks for open this ticket, which version of the module are you using?

**Comment by jonathanwilke** [comment]
6.0.0

**Comment by martvdmoosdijk** [comment]
We're having the same issue here on v5.7.9.

**Comment by alvarosabu** [comment]
Hi @jonathanwilke I'm not able to reproduce it locally, but can be because of the playground 
![Screenshot 2024-01-25 at 10 27 29](https://github.com/storyblok/storyblok-nuxt/assets/4699008/58090b07-f899-4611-9ada-e9c2df689626)

Would you be so kind as to create a proper reproduction link using https://stackblitz.com/edit/nuxt-3-quickstart-demo?file=README.md  so I can reproduce it?

Thanks

**Comment by jonathanwilke** [comment]
Hey, we solved the problem. We had defined a custom _paths_ property in our tsconfig and that was creating some issues including the one with your storyblok module. We removed it now and everything works fine. Thanks for your support anyway!

**Comment by Kristoffer95** [comment]
Issue still occurs on 6.0.6

**Comment by gbyesiltas** [comment]
> Hi, @Kristoffer95 @gbyesiltas maybe you could help us out with a minimal reproduction so I can take a look?
> 
> Thank you.

Hey, I will try to create a reproduction when I have the time. In the meantime, I was just playing around with a few things and updating the nuxt package from `3.11.1` to `3.11.2` actually fixed this issue for me 🤔 (then I had a type error with another package but I fixed that in a different way :D)

**Comment by alvarosabu** [comment]
Hi @Kristoffer95 could you please check if the solution that @jonathanwilke mention works for you?

> We had defined a custom paths property in our tsconfig and that was creating some issues including the one with your storyblok module. We removed it now and everything works fine.

**Comment by jonathanwilke** [comment]
Yes, this was the problem for me too! Thanks for the solution :)

**Comment by gbyesiltas** [comment]
Hey @alvarosabu, sorry for the wait. Here's a very simple reproduction: https://github.com/gbyesiltas/storyblok-688-repro

**Comment by alvarosabu** [comment]
Hey @gbyesiltas thanks for the link. Just for the future, I will kindly ask you to provide a stackblitz like this https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz. 

The problem with GitHub repo reproductions is that I normally check at least 10-15 issues a day, if I have to download, install, and run all the reproductions it becomes really time-consuming apart of all the files on my local machine, that's why we promote the use of solutions like https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz where the code is on the cloud, we can quickly check it and give feedback.

Thanks 🙏🏻

**Comment by alvarosabu** [comment]
I just updated the dependencies to the latest and it works again

```
"@storyblok/nuxt": "^6.0.10",
"nuxt": "3.11.2",
"vue": "3.4.26",
"vue-router": "4.3.2"
```

![Screenshot 2024-04-30 at 10 52 21](https://github.com/storyblok/storyblok-nuxt/assets/4699008/73a52a55-0e80-4e87-be1f-5c0b7349bc5f)

**Comment by gbyesiltas** [comment]
> Hey @gbyesiltas thanks for the link. Just for the future, I will kindly ask you to provide a stackblitz like this https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz.
> 
> The problem with GitHub repo reproductions is that I normally check at least 10-15 issues a day, if I have to download, install, and run all the reproductions it becomes really time-consuming apart of all the files on my local machine, that's why we promote the use of solutions like https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz where the code is on the cloud, we can quickly check it and give feedback.
> 
> Thanks 🙏🏻

@alvarosabu Yeah understandable :) I used VSCode to make sure the environment with the TypeScript and the Vue extensions would be the same. Though I probably could have made the reproduction based on the nuxt type-check command instead of the IDE intellisense
