### ISSUE TITLE
Type '{ accessToken: string; }' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by alvarosabu** [storyblok/storyblok-nuxt#73]
Hey there, there is a type error when adding the module on a `nuxt.config.ts` 

Repro: https://stackblitz.com/edit/github-mtfdou?file=nuxt.config.ts

```
npx nuxi info

Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@storyblok/nuxt@3.0.0-beta.2`
------------------------------
```
![Screenshot 2022-01-11 at 10 55 03](https://user-images.githubusercontent.com/4699008/148920871-37c5a8ac-1030-48ea-adcd-7f326a7e4600.png)

**Comment by awacode21** [comment]
i'm experiencing the same

**Comment by michaelpumo** [comment]
I get the same error along with some additional stuff in the terminal. Bummer because I'm following the guide here and it's just not working: https://github.com/storyblok/storyblok-nuxt/tree/next

<img width="1445" alt="Screenshot 2022-01-13 at 20 22 56" src="https://user-images.githubusercontent.com/4269460/149403826-48b63116-646c-431b-a842-8f75266b36ee.png">

**Comment by alvarosabu** [comment]
@michaelpumo you need to change `modules` for `buildModules`. Is a good opportunity to open a PR to update the documentation :)

**Comment by awacode21** [comment]
i get the same error on modules and buildModules. No difference.

**Comment by alvarosabu** [comment]
@awacode21  the type error or also the error regarding `Nuxt module should be a funciton` ?

**Comment by awacode21** [comment]
@alvarosabu i get the type error with both approaches. I don't get the `Nuxt module should be a function error` at all.

**Comment by michaelpumo** [comment]
> buildModules

I'm afraid that does not work either. At this point, it's hard to work out if the issues are with Storyblok or Nuxt 3 being in Beta. I think I'll wait for stable releases now. I can't take the pain! :)

**Comment by schietegal** [comment]
Same Problem, are there any quick solutions available?

**Comment by edoecohen** [comment]
@schietegal you can use the universal Storyblok JS SDK which works fine with Nuxt 3: https://github.com/storyblok/storyblok-js-client
That's what we're using until the issue mentioned above is fixed.
