### ISSUE TITLE
Enabling the @storyblok/nuxt module causes components to lose typings.

### ISSUE THREAD

**Issue by martvdmoosdijk** [storyblok/storyblok-nuxt#738]
### Describe the issue you're facing

Enabling the @storyblok/nuxt module causes components to lose typings. See attached video.

Related ticket: https://github.com/storyblok/storyblok-nuxt/issues/688

https://github.com/storyblok/storyblok-nuxt/assets/16029319/3f013e2d-b446-45b6-8794-58a233345f43

### Reproduction

https://github.com/martvdmoosdijk/nuxt-storyblok-bug-reproduction

### Steps to reproduce

1. Install dependencies `npm install`

2. Run app `npm run dev`

3. Notice that hovering over the `<MyComponent />` within [app.vue](./app.vue) shows the type of the component

```ts
(property) MyComponent: DefineComponent<__VLS_TypePropsToRuntimeProps<{
    name: string;
}>, {}, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., {}>
```

4. Enable/uncomment the @storyblok/nuxt module in the [nuxt config](./nuxt.config.ts)

5. Reload VSCode

6. Notice that hovering over the `<MyComponent />` within [app.vue](./app.vue) show that the component has an unknown type

```ts
(property) MyComponent: unknown
```

7. Types show up again once you disable the module and reload VSCode.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 310.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nodenv/versions/20.9.0/bin/node
    npm: 10.1.0 - ~/.nodenv/versions/20.9.0/bin/npm
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 121.0.6167.160
    Safari: 17.0

"@storyblok/nuxt": "^6.0.4",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Kristoffer95** [comment]
Same issue on version 6.0.6

**Comment by alvarosabu** [comment]
Hi @martvdmoosdijk @Kristoffer95 could you please check if this solution provided by the author of the original tickets works for you?

```
We had defined a custom paths property in our tsconfig and that was creating some issues including the one with your storyblok module. We removed it now and everything works fine.
```

**Comment by alvarosabu** [comment]
Hi @martvdmoosdijk thank you for confirming this, I'm gonna take a look to this since I was able to reproduce it

**Comment by gbyesiltas** [comment]
I linked a reproduction for this [here](https://github.com/storyblok/storyblok-nuxt/issues/688#issuecomment-2084718422). It seems like simply upgrading to nuxt `3.11.2` fixes the issue

**Comment by martvdmoosdijk** [comment]
Thank @alvarosabu. That seems to have done the trick!
