### ISSUE TITLE
Is Tailwind class binding possible through Storyblok?

### ISSUE THREAD

**Issue by telisjok** [storyblok/storyblok-nuxt#76]
I'm trying to develop some components that will be used by the content editors in Storyblok and there's a use case where we would like to define layout properties (using Tailwind's classes) through props that will be coming from Storyblok components.

As an example,
![image](https://user-images.githubusercontent.com/4696628/150532398-5732c772-08f2-4f20-9680-7aa9b6419522.png)
I am passing the `width` prop through storyblok giving a value of `w-1/2` which is a Tailwind class. As you see on the right the class is applied just fine to the element but there's no actual impact on the page. I have tried the same with many other classes (either for background or border colors or for text styling etc, tried to use Tailwind classes as props coming from Storyblok but didn't work).

My only guess is that Nuxt is a server side application and the CSS gets compiled on build time, therefore any new class binding to the DOM will not reflect the actual CSS that they represent. Is this right? If yes, is there a way to make this happen and work?

The code for the `widthSetter` component is as simple as that
```
<template>
  {{blok.width}}
  <div v-editable="blok" :class="[ blok.width ]">
    <component
      v-for="value in blok.blocks"
      :key="value._uid"
      :is="value.component"
      :blok="value"
    />
  </div>
</template>

<script lang="ts" setup>
const props = defineProps({
  blok: {
    type: Object,
    required: true,
  },
})
</script>
```

**Comment by jsthind** [comment]
@telisjok - were you able to get the Tailwind classes working? I am facing the same issue with the Tailwind classes coming in from Sotryblok, being rendered in HTML but missing the related CSS styles.

**Comment by chrisnoden** [comment]
The issue is that the Tailwind "compiler" (sorry, if that's not what it's called) doesn't know to add those classes to the build output because they are injected dynamically.

It's not a great solution, but for now my approach has been to create a vue/html page that is in my main templates directory called `_compiler.vue` and list all those classes that I make available to my Storyblok editors in there. Tailwind then compiles them into the build and they work.

eg
```
<script>
// This file exists purely to ensure certain tailwind classes are compiled
// namely ones that are injected by Storyblok but are not defined elsewhere in this code
</script>
<template>
    <div class="
        hidden
        font-medium font-bold font-normal italic underline text-white placeholder-white
        max-w-7xl max-w-6xl max-w-5xl max-w-4xl max-w-3xl
        h-4 h-6 h-8 h-12 h-16 h-20
        w-4 w-6 w-8 w-12 w-16 w-20
        border-b border-b-link border-b-primary border-b-gray-300 border-b-gray-50
        mt-0 mb-0 mt-4 mb-4 mt-8 mb-8 mt-12 mb-12 mt-16 mb-16
        px-2 px-4 px-12
        grid gap-0 gap-6 gap-16 grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-5
        items-start items-center items-end items-top
        bg-white bg-gray-50 bg-gray-100 bg-gray-200 bg-gray-300 bg-primary bg-secondary
    "></div>
</template>
```

**Comment by chrisnoden** [comment]
I don't know over what timescale you are comparing and I'm not a Tailwind expert, but newer Tailwind optimises the final CSS that is built - so only classes used in your monitored directories/files are compiled. These are configured in your `tailwind.config.js` file under the `content` directive.

If you use a tailwind class in any file that is matched by the rules in your `content` directive then they will also work via the Storyblok dynamic class inclusion method. So, if you already have a file that uses `px-8` then you can also use that via Storyblok. But if none of your normal components/pages use a class then you will need to include it in the Tailwind build via a route such as the one I suggest.
