### ISSUE TITLE
Cache version `cv=undefined` causes redirect

### ISSUE THREAD

**Issue by alvarosabu** [storyblok/storyblok-nuxt#776]
### Describe the issue you're facing

API calls with `cv=undefined` seem to cause redirect 301 on Nuxt with SSR

<img width="652" alt="redirect-issue" src="https://github.com/storyblok/storyblok-nuxt/assets/4699008/f5ca6941-7ddf-4a55-a0a4-ace9a902ae41">

### Reproduction

https://www.valkdeals.nl/en

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 261.88 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.3.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by alvarosabu** [comment]
Closes since is an expected behavior of the cdn

**Comment by awacode21** [comment]
@alvarosabu i am dealing with the same issue, did you ever found out how to fix this?

My Setup Vercel+Nuxt3(SSR)+Storyblok
