### ISSUE TITLE
Add the option to set default API version  (`draft` or `published`) from Nuxt Config and using an ENV variable

### ISSUE THREAD

**Issue by stefanobartoletti** [storyblok/storyblok-nuxt#788]
### Description

At the moment, by reading the docs, the suggested way to get your API version (`draft` or `published`) is to set an option when retrieving the stories, like this

```js
const resolveRelations = [
  // My resolveRalations
]

const story = await useAsyncStoryblok(
  'my_story',
  {
    version: ''draft, // or 'published'
    resolve_relations: resolveRelations,
  },
  {
    resolveRelations,
  },
)
```

Having the version hardcoded seems to be not optimal, as you will typically need a variable value between your development and production environment.

I tried to use an environment variable, something like this:

```js
const resolveRelations = [
  // My resolveRalations
]

const story = await useAsyncStoryblok(
  'my_story',
  {
    version: process.env.SB_STORY_VERSION
    resolve_relations: resolveRelations,
  },
  {
    resolveRelations,
  },
)
```

and

```env
#.env
SB_STORY_VERSION=draft
```

But apparently, no matter what value I use here, I always get thedefault  `published` stories (I can tell because hey do not have the `_editable` values).

I'm not sure if I'm doing something wrong here (maybe environment variables are not supported within the storybook functions?), some insight about this is welcome

### Suggested solution or improvement

I have a suggestion that may help solve this in a more general way.

Considering that:
- you will typically need only one version in each environment (`draft` in local development, and `published` in production).
- you may need to fetch stories in multiple places in your site/app.

My suggestion is to add a config option to the Nuxt Module, where you can select your default story version to be used across your app, pretty much like you already do with your API token, something like this:

```js
export default defineNuxtConfig({
  modules: [
    '@storyblok/nuxt',
  ],
  storyblok: {
    accessToken: process.env.SB_API_TOKEN, // Already present 
    apiVersion: process.env.SB_API_VERSION // suggested new option, supporting a value from an environment variable
  },
})
```

So now whenever you call the provided functions `useStoryblokApi`, `useAsyncStoryblok`  and so on, you will not need to define the version each time because this value is taken from the default config.

### Additional context

I may have done something wrong in my own setup, if it is actually possible to use an environment variable even inside `useStoryblokApi`, `useAsyncStoryblok` please let me know how :)

Thanks for your support and have a nice day 😀

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
Hi @stefanobartoletti 💜

Let's try something! Is it possible that the call is being made in the client side? If that's the case, did you try using the .env variables with this prefix: `NUXT_PUBLIC_`?

**Comment by alvarosabu** [comment]
Hi @stefanobartoletti, what I recommend you do is to add the variables to the `runtimeConfig.public` on the `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      storyblokVersion: process.env.STORYBLOK_VERSION || 'published',
    },
  },
})
``` 

And then:

```ts
const config = useRuntimeConfig()

const story = await useAsyncStoryblok(
  'blog',
  { version: config.public.storyblokVersion, resolve_relations: 'overview.featured_story' },
  { resolveRelations: 'overview.featured_story' },
)

//or 

const { data: articles } = await storyblokApi.get('cdn/stories', {
  version: config.public.storyblokVersion,
  starts_with: 'blog',
  is_startpage: false,
})
```

**Comment by stefanobartoletti** [comment]
Thanks to both of you for your answers!

I tried both solutions and the one that works best in my implementation is @alvarosabu.

I think that this is some valuable information that maybe could also be included in the module readme, so even other people could benefit from it (I think it could be a common need to differentiate between environments)

Anyway, thanks for your support 🙏🏻

**Comment by Dawntraoz** [comment]
Perfect! As @stefanobartoletti mentioned, it will be nice to add it to the README. Since you already gave an example, can you update the README with the `runtimeConfig` example @alvarosabu? Thanks in advance. You are the best!

PS: Just to let you know, we had this workaround in the last part of the UT, but for another variable (NODE_ENV) https://www.storyblok.com/tp/create-a-preview-environment-for-your-nuxt-3-website/.
