### ISSUE TITLE
Missing type for componetsDir

### ISSUE THREAD

**Issue by claudiabdm** [storyblok/storyblok-nuxt#821]
### Describe the issue you're facing

Hello! 

I'm using Typescript in my Nuxt + Storyblok project and I just came across a type error when setting `componentsDir` to false in storyblok option in `nuxt.config.ts` file. 

<img width="547" alt="Screenshot 2024-04-23 at 16 09 10" src="https://github.com/storyblok/storyblok-nuxt/assets/44007726/11bf8cd9-8387-49f8-91ad-53c59f2f8894">

Based on the [README instructions](https://github.com/storyblok/storyblok-nuxt/blob/main/README.md#1-creating-and-linking-your-components-to-storyblok-visual-editor), the type of `componentsDir` should take into account the `false` option as well but it seems that is only of type `string`. 
https://github.com/storyblok/storyblok-nuxt/blob/098dc975777d5c53969c2bbbd26437041d107e23/src/module.ts#L18

Thank you! 

### Reproduction

https://stackblitz.com/edit/nuxt-starter-thqbyh?file=nuxt.config.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by alvarosabu** [comment]
Hi @claudiabdm I want to apologize for the confusion caused, the `componentsDir` is meant to be a string containing the route for the components. I just corrected the README.md in the PR above.

**Comment by claudiabdm** [comment]
Thank you!
