### ISSUE TITLE
@next Proposal: Adapt to new Nuxt module-builder

### ISSUE THREAD

**Issue by alvarosabu** [storyblok/storyblok-nuxt#84]
Hey there,

Nuxt3 released recently a [module-builder](https://v3.nuxtjs.org/docs/advanced/modules), which has been used on the next version of several modules ([Nuxt lazyload](https://github.com/nuxt-modules/lazy-load) and [nuxt-algolia](https://github.com/nuxt-community/algolia-module/pull/12)) I will recommend we upgrade the current code to the standard format.

## Benefits
- Reduce dependencies and compatibility issues with nuxt3 (I talked with DanielRoe, things should be more stable with this module-builder)
- Typescript support right away
- Standard way of creating modules, easier for contributing

If you agree I can prepare a PR with the migration. 

Cheers

**Comment by Baroshem** [comment]
I completely agree with Alvaro.

Module Builder seems to be much more stable right now as many new modules are being created using it (Algolia, Partytown, Harlem, Prismic, etc). I would recommend rewriting the module using the module builder pattern to avoid current issues with the module.

If you need any help I will be glad to help with the migration :)

**Comment by alexjoverm** [comment]
Hey @alvarosabu! Thanks a lot for opening this issue, @Baroshem also suggested it, and feels like the way to go. Actually, that's something I worked on already in branch https://github.com/storyblok/storyblok-nuxt/tree/feat/use-storyblok-js.

Right now we're restructuring the underlying SDKs and likely we'll have a separate repo for nuxt 3 SDK. I'll keep you posted soon :)

**Comment by alvarosabu** [comment]
That sounds great, let me know if u need help. Cheers

**Comment by Dawntraoz** [comment]
As this is already implemented I will close this issue folks @alvarosabu @Baroshem 🚀
