### ISSUE TITLE
Breaks component auto imports

### ISSUE THREAD

**Issue by P4sca1** [storyblok/storyblok-nuxt#90]
v3.0.2 breaks Nuxt.js component auto imports. I start to get errors like custom component `Sidebar` not found, which is auto imported when I disable the build module.
This may be because I configured it using `components: true` instead of with the array variant. 
Would be great if the auto import feature that this module provides with the storyblok subdirectory could be documented in the README.

**Comment by alvarosabu** [comment]
Hi, @P4sca1 thanks for raising this, is this still valid for v5?

**Comment by alvarosabu** [comment]
Closed as no further updates where given

**Comment by notorigine** [comment]
I believe this is still happening as of today using this stack :
- Nuxt : ^2.15.8
- @storyblok/nuxt-2 : ^2.0.15 

Expected behavior: non-Storyblok components should be autoimported without errors/warnings
Actual behavior: non-Storyblok components are not autoimported and are causing errors/warnings
