### ISSUE TITLE
[Docs] Use native structuredClone instead of clone-deep

### ISSUE THREAD

**Issue by davidsandoz** [storyblok/storyblok-nuxt#906]
### Description

As a developer using Storyblok SDK, I want to limit the amount of external dependencies so that the bundle size of my app is as small as possible, and to reduce the possible points of failure.

In the [Rendering Rich Text section of the README](https://github.com/storyblok/storyblok-nuxt?tab=readme-ov-file#rendering-rich-text), there's an example featuring the usage of the [clone-deep](https://github.com/jonschlinkert/clone-deep) library.

However, there's a native function [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone) that is widely available to all browsers.

### Suggested solution or improvement

If there's no specific reason for using the `clone-deep` library instead of the native `structuredClone` function, replace the usage of `clone-deep` with `structuredClone`.

If there's a good reason, then provide an explanation in the README.

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by alvarosabu** [comment]
Hi @davidsandoz thanks for reaching out.

We are currently implementing a new richtext for the whole ecosystem which doesn't depend on `clone-deep`. It is already available on `@storyblok/vue` but Im currently working on adding it to this module

**Comment by davidsandoz** [comment]
@alvarosabu Thanks for your answer! Until this gets added to the module, do you see any issue with using `structuredClone` instead `clone-deep`?

**Comment by alvarosabu** [comment]
@davidsandoz https://github.com/storyblok/storyblok-nuxt/pull/923
