### ISSUE TITLE
Im getting this error during load. 

### ISSUE THREAD

**Issue by bootsmann1995** [storyblok/storyblok-nuxt#92]
I have followed your setup, but i'm getting this error when loading any page.

![image](https://user-images.githubusercontent.com/65391517/157022887-0a163dec-d7bc-4b4d-9f50-20d37b1afaaf.png)

**Comment by deodat** [comment]
I'm getting the same error too (just after installing pinia and @pinia/nuxt)

**Comment by pascalwengerter** [comment]
Could you add more context here (ranging from your machine's OS to npm/node version, content of the package.json etc? :)
