### ISSUE TITLE
Add Typescript types

### ISSUE THREAD

**Issue by P4sca1** [storyblok/storyblok-nuxt#93]
Would be great if this module could expose TypeScript types for Nuxt.js configuration, additions to Nuxt Context and exported methods.

**Comment by P4sca1** [comment]
Progress started in #33

**Comment by alvarosabu** [comment]
Hey there, we added better Typescript support not so long ago, is this still needed? If so feel free to re-open with the suggested changes.

**Comment by m-shum** [comment]
> Hey there, we added better Typescript support not so long ago, is this still needed? If so feel free to re-open with the suggested changes.

Could you point out the docs for this, if there are any? Where are we supposed to import the types from? It's pretty straightforward with the React SDK but this one, not so much.
