### ISSUE TITLE
[vite] Internal server error: Missing "./source" export in "storyblok-js-client" package 

### ISSUE THREAD

**Issue by mkuItra** [storyblok/storyblok-nuxt#97]
Error: [vite] Internal server error: Missing "./source" export in "storyblok-js-client" package 

Been following this https://www.storyblok.com/mp/storyblok-meets-vue3-nuxt3

Node js lts

**Comment by alvarosabu** [comment]
Hi, @mkuItra thanks for raising this. 

To be able to help you, could you provide a reproduction link (you can fork the official [Stackblitz](https://stackblitz.com/edit/nuxt-ultimate-tutorial-part-3?file=README.md)) 

Please run this command to get more info about your packages

`npx envinfo --system --npmPackages '{nuxt,@storyblok/*, vue}' --binaries --browsers`

**Comment by alvarosabu** [comment]
Closing due inactivity, please feel free to reopen is still relevant with a reproduction link and `npx envinfo` output. Thanks
